import LeanLab.Riemann.BalazardSaias
import LeanLab.Riemann.AnalyticLogBranch
import LeanLab.Riemann.ReciprocalZetaSubpower
import LeanLab.Riemann.TruncatedPerron
import LeanLab.Riemann.BalazardSaiasContour
import LeanLab.Riemann.BaezDuarteReverse
import LeanLab.Riemann.BaezDuarteForward
import LeanLab.Riemann.BaezDuarteForwardLimit
import LeanLab.Riemann.BurnolLowerBound
import LeanLab.Riemann.BurnolA
import LeanLab.Riemann.BurnolHardy

set_option linter.style.header false
set_option linter.style.longLine false

/-!
# Trusted-dependency audit for fixed-gap RH work

The build log for this module must list only Lean's standard extensionality, choice, and quotient
principles for each theorem below.
-/

#print axioms riemannZeta_eq_zetaAbelContinuationFormula
#print axioms LeanLab.Riemann.riemannZeta_eq_zetaAbelContinuationFormula_of_re_pos
#print axioms LeanLab.Riemann.hasMellin_fractionalPartKernel_one
#print axioms LeanLab.Riemann.hasMellin_baezDuarteKernel
#print axioms LeanLab.Riemann.expNeg_quasiMeasurePreserving
#print axioms LeanLab.Riemann.eLpNorm_weightedLogForwardFun
#print axioms LeanLab.Riemann.weightedLogForward_inverse
#print axioms LeanLab.Riemann.weightedLogPullback_coeFn
#print axioms LeanLab.Riemann.weightedLogPullback_symm_coeFn
#print axioms LeanLab.Riemann.norm_baezDuarteFourierMellinL2
#print axioms LeanLab.Riemann.mellin_criticalLine_eq_fourier
#print axioms LeanLab.Riemann.baezDuarteVerticalMajorant_memLp
#print axioms LeanLab.Riemann.baezDuarteCriticalLineZetaZeroOrdinates_countable
#print axioms LeanLab.Riemann.ae_tendsto_baezDuarteZetaRatio_one
#print axioms LeanLab.Riemann.baezDuarteMobiusApprox_two_mul_eq_dirichletTail_of_one_lt
#print axioms LeanLab.Riemann.baezDuarte_weightedTail_norm_sq_le
#print axioms LeanLab.Riemann.tendsto_norm_zero_of_baezDuarte_weightedTail
#print axioms LeanLab.Riemann.baezDuarte_finsupp_norm_sq_le_of_weighted
#print axioms Complex.exists_norm_digamma_le_log
#print axioms LeanLab.Riemann.exists_norm_Gamma_div_le_rpow_of_re_mem_Icc
#print axioms LeanLab.Riemann.exists_norm_baezDuarteZetaRatio_le_rpow
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatio_bound
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatioIntegrand_majorant
#print axioms LeanLab.Riemann.differentiable_zetaPoleRemoved
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.norm_Gamma_mul_cos_one_sub_mul_I_le
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_mul_I_le_rpow
#print axioms Complex.zeta_minus_pole_entire_growth
#print axioms LeanLab.Riemann.fioriMidpointQuotient_zetaPoleRemoved_growth
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_div_criticalLine_le_rpow
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le
#print axioms LeanLab.Riemann.burnolMobiusMajorant_memLp
#print axioms LeanLab.Riemann.tendsto_natCast_rpow_neg_delta_div_three
#print axioms Complex.exists_differentiableOn_eqOn_exp_comp_of_isSimplyConnected
#print axioms LeanLab.Riemann.exists_riemannZeta_differentiableLogBranch
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_reciprocalZeta_subpower_bound
#print axioms LeanLab.Riemann.LSeries_moebius_eq_reciprocal_riemannZeta
#print axioms LeanLab.Riemann.norm_perronIntegrand_vertical_integral_le_of_neg
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_le_of_lt_one
#print axioms LeanLab.Riemann.integral_inv_boundary_rect_eq_two_pi_mul_I
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_sub_one_le_of_one_lt
#print axioms LeanLab.Riemann.hasSum_integral_mobiusPerronSeriesTerm
#print axioms LeanLab.Riemann.exists_mobiusDirichletPartialSum_sub_truncatedPerronIntegral_le
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_balazardSaias_specialized_bound_compiled
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le_compiled
#print axioms LeanLab.Riemann.riemannZeta_ne_zero_of_baezDuarteComplexTarget_mem_closure
#print axioms LeanLab.Riemann.baezDuarteComplexTarget_mem_closure_imp_riemannHypothesis
#print axioms LeanLab.Riemann.fourier_toLp_eq_toLp_fourier
#print axioms LeanLab.Riemann.RiemannHypothesis.cauchySeq_baezDuarteMobiusApproxComplexL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_baezDuarteMobiusApproxL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_weightedMobiusTransformedError_majorant
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_scaledWeightedLimitTransform_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_mobiusApproxL2_close_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteComplexTargetL2_mem_kernelClosure
#print axioms LeanLab.Riemann.riemannHypothesis_iff_baezDuarteComplexTarget_mem_kernelClosure
#print axioms LeanLab.Riemann.baezDuarteFiniteComplexKernelSpan_le_burnolKernelSpan
#print axioms LeanLab.Riemann.burnolDistance_inv_natCast_le_baezDuarteNaturalDistance
#print axioms LeanLab.Riemann.tendsto_natCast_inv_nhdsWithin_Ioi_zero
#print axioms LeanLab.Riemann.burnolA_eq_tailIntegral_sub_fractionalPart
#print axioms LeanLab.Riemann.burnolA_memLp_two_positiveHalfLine
#print axioms LeanLab.Riemann.mellin_burnolComplexFractionalPartTail_eq
#print axioms LeanLab.Riemann.hasMellin_burnolA
#print axioms LeanLab.Riemann.norm_burnolHardyInverseMultiplier
#print axioms LeanLab.Riemann.hasMellin_burnolChiOne
#print axioms LeanLab.Riemann.burnolHardyInverseL2_target
#print axioms LeanLab.Riemann.burnolHardyInverseL2_kernel
#print axioms LeanLab.Riemann.burnolHardyInverseL2_map_kernelSpan
#print axioms LeanLab.Riemann.burnolDistance_eq_modelDistance
