import LeanLab.Riemann.BalazardSaias
import LeanLab.Riemann.DeBruijnNewman
import LeanLab.Riemann.DeBruijnNewmanHeat
import LeanLab.Riemann.DeBruijnNewmanZeros
import LeanLab.Riemann.DeBruijnNewmanThreshold
import LeanLab.Riemann.DeBruijnNewmanForward
import LeanLab.Riemann.DeBruijnNewmanUpperHalf
import LeanLab.Riemann.DeBruijnNewmanGeneralStrip
import LeanLab.Riemann.DeBruijnNewmanDynamics
import LeanLab.Riemann.DeBruijnNewmanPolymathCriterion
import LeanLab.Riemann.DeBruijnNewmanHermiteSplitting
import LeanLab.Riemann.DeBruijnNewmanTableRowCertificates
import LeanLab.Riemann.DeBruijnNewmanPolymathRiemannSiegel
import LeanLab.Riemann.DeBruijnNewmanPolymathHeatKernel
import LeanLab.Riemann.DeBruijnNewmanPolymathRiemannSiegelContour
import LeanLab.Riemann.DeBruijnNewmanLiMoments
import LeanLab.Riemann.DeBruijnNewmanThirdLi
import LeanLab.Riemann.DeBruijnNewmanLiCriterion
import LeanLab.Riemann.DeBruijnNewmanHeatLiMonotonicity
import LeanLab.Riemann.FinitePowerSumRigidity
import LeanLab.Riemann.H6GapVelocityAudit
import LeanLab.Riemann.H6PositiveCoshLiAudit
import LeanLab.Riemann.H6ReverseHeatLiAudit
import LeanLab.Riemann.XiKernelLogConcavityAudit
import LeanLab.Riemann.XiKernelStrictLogConcavity
import LeanLab.Riemann.XiKernelPF5Falsification
import LeanLab.Riemann.LiZeroDivisor
import LeanLab.Riemann.LiHadamard
import LeanLab.Riemann.LiZeroFormula
import LeanLab.Riemann.LiSymmetricZeroFormula
import LeanLab.Riemann.LiReverseCriterion
import LeanLab.Riemann.LiWeilGram
import LeanLab.Riemann.WeilTestAlgebra
import LeanLab.Riemann.WeilConvolution
import LeanLab.Riemann.WeilStripClass
import LeanLab.Riemann.WeilExplicitIntegrand
import LeanLab.Riemann.WeilZeroCutoff
import LeanLab.Riemann.WeilGaussianHeight
import LeanLab.Riemann.WeilGaussianExplicitFormula
import LeanLab.Riemann.WeilSymmetricGaussianFamily
import LeanLab.Riemann.WeilFiniteGaussianTestCore
import LeanLab.Riemann.WeilGaussianQuadraticPositivity
import LeanLab.Riemann.WeilGaussianPositivityCriterion
import LeanLab.Riemann.WeilGaussianFixedWidthCriterion
import LeanLab.Riemann.WeilCompactLaplaceSeparator
import LeanLab.Riemann.WeilCompactLaplaceZeroCutoff
import LeanLab.Riemann.WeilCompactLaplaceArithmeticFormula
import LeanLab.Riemann.WeilCompactPositivityCriterion
import LeanLab.Riemann.WeilGaussianPrimeKernelSignAudit
import LeanLab.Riemann.PolsonGGCContinuationAudit
import LeanLab.Riemann.FreedmanGreenLiftAudit
import LeanLab.Riemann.AnalyticLogBranch
import LeanLab.Riemann.ReciprocalZetaSubpower
import LeanLab.Riemann.TruncatedPerron
import LeanLab.Riemann.BalazardSaiasContour
import LeanLab.Riemann.BaezDuarteReverse
import LeanLab.Riemann.BaezDuarteForward
import LeanLab.Riemann.BaezDuarteForwardLimit
import LeanLab.Riemann.BaezDuarteQTwo
import LeanLab.Riemann.BurnolLowerBound
import LeanLab.Riemann.BurnolA
import LeanLab.Riemann.BurnolHardy
import LeanLab.Riemann.BurnolY
import LeanLab.Riemann.BurnolGram
import LeanLab.Riemann.BurnolFiniteLowerBound
import LeanLab.Riemann.BurnolFullLowerBound
import LeanLab.Riemann.M2ProjectionNormAudit
import LeanLab.Riemann.M2LadderFrequencyAudit
import LeanLab.Riemann.M2GramGeometry
import LeanLab.Riemann.M2SparseObstruction

set_option linter.style.header false
set_option linter.style.longLine false

/-!
# Trusted-dependency audit for fixed-gap RH work

The build log for this module must list only Lean's standard extensionality, choice, and quotient
principles for each theorem below.
-/

#print axioms riemannZeta_eq_zetaAbelContinuationFormula
#print axioms LeanLab.Riemann.riemannZeta_eq_zetaAbelContinuationFormula_of_re_pos
#print axioms LeanLab.Riemann.hasMellin_fractionalPartKernel_one
#print axioms LeanLab.Riemann.hasMellin_baezDuarteKernel
#print axioms LeanLab.Riemann.expNeg_quasiMeasurePreserving
#print axioms LeanLab.Riemann.eLpNorm_weightedLogForwardFun
#print axioms LeanLab.Riemann.weightedLogForward_inverse
#print axioms LeanLab.Riemann.weightedLogPullback_coeFn
#print axioms LeanLab.Riemann.weightedLogPullback_symm_coeFn
#print axioms LeanLab.Riemann.norm_baezDuarteFourierMellinL2
#print axioms LeanLab.Riemann.mellin_criticalLine_eq_fourier
#print axioms LeanLab.Riemann.baezDuarteVerticalMajorant_memLp
#print axioms LeanLab.Riemann.baezDuarteCriticalLineZetaZeroOrdinates_countable
#print axioms LeanLab.Riemann.ae_tendsto_baezDuarteZetaRatio_one
#print axioms LeanLab.Riemann.baezDuarteMobiusApprox_two_mul_eq_dirichletTail_of_one_lt
#print axioms LeanLab.Riemann.baezDuarte_weightedTail_norm_sq_le
#print axioms LeanLab.Riemann.tendsto_norm_zero_of_baezDuarte_weightedTail
#print axioms LeanLab.Riemann.baezDuarte_finsupp_norm_sq_le_of_weighted
#print axioms Complex.exists_norm_digamma_le_log
#print axioms LeanLab.Riemann.exists_norm_Gamma_div_le_rpow_of_re_mem_Icc
#print axioms LeanLab.Riemann.exists_norm_baezDuarteZetaRatio_le_rpow
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatio_bound
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatioIntegrand_majorant
#print axioms LeanLab.Riemann.differentiable_zetaPoleRemoved
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.norm_Gamma_mul_cos_one_sub_mul_I_le
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_mul_I_le_rpow
#print axioms Complex.zeta_minus_pole_entire_growth
#print axioms LeanLab.Riemann.fioriMidpointQuotient_zetaPoleRemoved_growth
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_div_criticalLine_le_rpow
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le
#print axioms LeanLab.Riemann.burnolMobiusMajorant_memLp
#print axioms LeanLab.Riemann.tendsto_natCast_rpow_neg_delta_div_three
#print axioms Complex.exists_differentiableOn_eqOn_exp_comp_of_isSimplyConnected
#print axioms LeanLab.Riemann.exists_riemannZeta_differentiableLogBranch
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_reciprocalZeta_subpower_bound
#print axioms LeanLab.Riemann.LSeries_moebius_eq_reciprocal_riemannZeta
#print axioms LeanLab.Riemann.norm_perronIntegrand_vertical_integral_le_of_neg
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_le_of_lt_one
#print axioms LeanLab.Riemann.integral_inv_boundary_rect_eq_two_pi_mul_I
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_sub_one_le_of_one_lt
#print axioms LeanLab.Riemann.hasSum_integral_mobiusPerronSeriesTerm
#print axioms LeanLab.Riemann.exists_mobiusDirichletPartialSum_sub_truncatedPerronIntegral_le
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_balazardSaias_specialized_bound_compiled
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le_compiled
#print axioms LeanLab.Riemann.riemannZeta_ne_zero_of_baezDuarteComplexTarget_mem_closure
#print axioms LeanLab.Riemann.baezDuarteComplexTarget_mem_closure_imp_riemannHypothesis
#print axioms LeanLab.Riemann.fourier_toLp_eq_toLp_fourier
#print axioms LeanLab.Riemann.RiemannHypothesis.cauchySeq_baezDuarteMobiusApproxComplexL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_baezDuarteMobiusApproxL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_weightedMobiusTransformedError_majorant
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_scaledWeightedLimitTransform_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_mobiusApproxL2_close_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteComplexTargetL2_mem_kernelClosure
#print axioms LeanLab.Riemann.riemannHypothesis_iff_baezDuarteComplexTarget_mem_kernelClosure
#print axioms LeanLab.Riemann.hasMellin_baezDuarteQTwoTargetFunction
#print axioms LeanLab.Riemann.hasMellin_baezDuarteQTwoKernelFunction
#print axioms LeanLab.Riemann.baezDuarteQTwoPhysicalCLM_target_eq
#print axioms LeanLab.Riemann.baezDuarteQTwoPhysicalCLM_kernel_eq
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteQTwoComplexTargetL2_mem_kernelClosure
#print axioms LeanLab.Riemann.riemannZeta_ne_zero_of_baezDuarteQTwoComplexTarget_mem_closure
#print axioms LeanLab.Riemann.baezDuarteQTwoComplexTarget_mem_closure_imp_riemannHypothesis
#print axioms LeanLab.Riemann.riemannHypothesis_iff_baezDuarteQTwoComplexTarget_mem_kernelClosure
#print axioms LeanLab.Riemann.baezDuarteFiniteComplexKernelSpan_le_burnolKernelSpan
#print axioms LeanLab.Riemann.burnolDistance_inv_natCast_le_baezDuarteNaturalDistance
#print axioms LeanLab.Riemann.tendsto_natCast_inv_nhdsWithin_Ioi_zero
#print axioms LeanLab.Riemann.burnolA_eq_tailIntegral_sub_fractionalPart
#print axioms LeanLab.Riemann.burnolA_memLp_two_positiveHalfLine
#print axioms LeanLab.Riemann.mellin_burnolComplexFractionalPartTail_eq
#print axioms LeanLab.Riemann.hasMellin_burnolA
#print axioms LeanLab.Riemann.norm_burnolHardyInverseMultiplier
#print axioms LeanLab.Riemann.hasMellin_burnolChiOne
#print axioms LeanLab.Riemann.burnolHardyInverseL2_target
#print axioms LeanLab.Riemann.burnolHardyInverseL2_kernel
#print axioms LeanLab.Riemann.burnolHardyInverseL2_map_kernelSpan
#print axioms LeanLab.Riemann.burnolDistance_eq_modelDistance
#print axioms LeanLab.Riemann.ae_burnolAPhaseMultiplier_eq_source
#print axioms LeanLab.Riemann.burnolAPhaseL2_burnolPsiL2_eq_hardySquare
#print axioms LeanLab.Riemann.tendsto_burnolPreY
#print axioms LeanLab.Riemann.burnolAPhaseL2_burnolY_coeFn
#print axioms LeanLab.Riemann.norm_burnolYTransformed_sub_V_cpow_le
#print axioms LeanLab.Riemann.norm_burnolYTransformed_le_large
#print axioms LeanLab.Riemann.inner_burnolY_normalizedModelKernel
#print axioms LeanLab.Riemann.burnolY_mem_modelKernelSpan_orthogonal
#print axioms LeanLab.Riemann.tendsto_inner_burnolX
#print axioms LeanLab.Riemann.burnolChiOnePhase_isBigO_sq
#print axioms LeanLab.Riemann.burnolAPhaseL2_chiOne
#print axioms LeanLab.Riemann.tendsto_sqrtLog_inner_chiOne_burnolX
#print axioms LeanLab.Riemann.burnolHilbertMatrix_isUnit_det
#print axioms LeanLab.Riemann.burnolHilbertMatrix_inv_zero_zero
#print axioms LeanLab.Riemann.tendsto_burnolGramMatrix_inv
#print axioms LeanLab.Riemann.tendsto_burnolBlockGramMatrix
#print axioms LeanLab.Riemann.tendsto_burnolBlockGramMatrix_inv
#print axioms LeanLab.Riemann.tendsto_burnolFiniteGramMatrix
#print axioms LeanLab.Riemann.burnolFiniteHilbertMatrix_isUnit_det
#print axioms LeanLab.Riemann.tendsto_burnolFiniteGramMatrix_inv
#print axioms LeanLab.Riemann.analyticOrderAt_riemannZeta_ne_top_of_isNontrivialZero
#print axioms LeanLab.Riemann.norm_burnolFiniteZetaProjection_le_distance
#print axioms LeanLab.Riemann.RiemannHypothesis.burnolDistance_liminf_ge_finset
#print axioms LeanLab.Riemann.RiemannHypothesis.burnolDistance_liminf_ge_fullZeroSum
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteNaturalDistance_liminf_ge_fullZeroSum
#print axioms LeanLab.Riemann.exists_symmetric_idempotent_not_maxNorm_nonexpansive
#print axioms LeanLab.Riemann.not_m2AuditWongPThree_maxNorm_nonexpansive
#print axioms LeanLab.Riemann.not_m2Audit_carvill_source_frequency_lower_bound
#print axioms LeanLab.Riemann.riemannXi_ne_zero_of_isTrivialZeroPoint
#print axioms LeanLab.Riemann.isNontrivialZero_iff_riemannXi_eq_zero
#print axioms LeanLab.Riemann.analyticOrderAt_riemannXi_ne_top
#print axioms LeanLab.Riemann.riemannXiZeroDivisor_apply
#print axioms LeanLab.Riemann.support_riemannXiZeroDivisor
#print axioms LeanLab.Riemann.riemannXiZeroMultiplicity_one_sub
#print axioms LeanLab.Riemann.riemannXi_eq_complex_riemannXi
#print axioms LeanLab.Riemann.riemannXi_divisor_toNat_eq_zeroMultiplicity
#print axioms LeanLab.Riemann.exists_riemannXiDivisorZeroIndex_val_iff
#print axioms LeanLab.Riemann.riemannXi_entireOfOrderAtMost_one
#print axioms LeanLab.Riemann.summable_riemannXiDivisorZeroIndex_norm_inv_sq
#print axioms LeanLab.Riemann.exists_riemannXi_hadamard_factorization
#print axioms LeanLab.Riemann.exists_riemannXi_logDeriv_eq_polynomial_derivative_add_tsum
#print axioms LeanLab.Riemann.summableLocallyUniformlyOn_riemannXiLogDerivZeroDerivativeTerm
#print axioms LeanLab.Riemann.iteratedDeriv_tsum_riemannXiLogDerivZeroTerm
#print axioms LeanLab.Riemann.liCoefficientCandidate_eq_finset_sum_iteratedDeriv_logDeriv
#print axioms LeanLab.Riemann.iteratedDeriv_logDeriv_riemannXi_eq_hadamard_zero_formula
#print axioms LeanLab.Riemann.exists_liCoefficientCandidate_eq_hadamard_zero_formula
#print axioms LeanLab.Riemann.not_summable_liRawZeroTerm_one_nat_succ
#print axioms LeanLab.Riemann.liRawZeroTerm_pair_quarter_two
#print axioms LeanLab.Riemann.riemannXiDivisorZeroReflectEquiv
#print axioms LeanLab.Riemann.summable_riemannXiSymmetrizedLiZeroTerm
#print axioms LeanLab.Riemann.liCoefficientCandidate_eq_tsum_riemannXiSymmetrizedLiZeroTerm
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_eq_tsum_normSq
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_im_eq_zero
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.exists_even_gt_forall_circle_pow_dist_one_lt
#print axioms LeanLab.Riemann.norm_liZeroTransform_le_one_iff
#print axioms LeanLab.Riemann.finite_riemannXiLiOrbitRadius_superlevel
#print axioms LeanLab.Riemann.norm_tsum_indicator_compl_riemannXiSymmetrizedLiZeroTerm_le
#print axioms LeanLab.Riemann.three_quarters_mul_orbitRadius_pow_lt_dominant_pow_re
#print axioms LeanLab.Riemann.exists_liCoefficientCandidate_re_neg_of_divisorZero_re_ne_half
#print axioms LeanLab.Riemann.riemannHypothesis_of_forall_liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.riemannHypothesis_iff_forall_liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.liWeilGramTerm_eq_symmetrized
#print axioms LeanLab.Riemann.summable_liWeilGramTerm
#print axioms LeanLab.Riemann.liWeilGramTerm_comm
#print axioms LeanLab.Riemann.liWeilGram_comm
#print axioms LeanLab.Riemann.liWeilGram_eq_liCoefficients
#print axioms LeanLab.Riemann.liWeilGram_diagonal
#print axioms LeanLab.Riemann.RiemannHypothesis.liWeilGramTerm_re_eq
#print axioms LeanLab.Riemann.RiemannHypothesis.liWeilQuadraticIntegrand_eq_normSq
#print axioms LeanLab.Riemann.summable_liWeilQuadraticIntegrand
#print axioms LeanLab.Riemann.RiemannHypothesis.summable_liWeilCombination_normSq
#print axioms LeanLab.Riemann.liWeilQuadratic_eq_tsum_integrand
#print axioms LeanLab.Riemann.RiemannHypothesis.liWeilQuadratic_eq_tsum_normSq
#print axioms LeanLab.Riemann.RiemannHypothesis.liWeilQuadratic_nonneg
#print axioms LeanLab.Riemann.liWeilQuadratic_single_one
#print axioms LeanLab.Riemann.riemannHypothesis_iff_forall_liWeilQuadratic_nonneg
#print axioms LeanLab.Riemann.weilInvolution_involution_of_pos
#print axioms LeanLab.Riemann.weilInvolution_involution_not_at_zero
#print axioms LeanLab.Riemann.mellinConvergent_weilInvolution_iff
#print axioms LeanLab.Riemann.mellin_weilInvolution
#print axioms LeanLab.Riemann.mellin_weilInvolution_zero
#print axioms LeanLab.Riemann.mellin_weilInvolution_one
#print axioms LeanLab.Riemann.mellin_conj
#print axioms LeanLab.Riemann.mellinConvergent_conj_iff
#print axioms LeanLab.Riemann.mellin_weilStar
#print axioms LeanLab.Riemann.mellinConvergent_weilStar_iff
#print axioms LeanLab.Riemann.mellin_weilStar_criticalLine
#print axioms LeanLab.Riemann.mellinConvergent_iff_integrable_mellinLogLift
#print axioms LeanLab.Riemann.mellin_eq_integral_mellinLogLift
#print axioms LeanLab.Riemann.weilConvolution_exp_neg
#print axioms LeanLab.Riemann.mellinLogLift_weilConvolution
#print axioms LeanLab.Riemann.mellinConvergent_weilConvolution
#print axioms LeanLab.Riemann.mellin_weilConvolution
#print axioms LeanLab.Riemann.mellin_weilConvolution_star
#print axioms LeanLab.Riemann.mellin_weilConvolution_star_criticalLine
#print axioms LeanLab.Riemann.mellin_weilAutocorrelation_criticalLine
#print axioms LeanLab.Riemann.isOpen_weilOpenStrip
#print axioms LeanLab.Riemann.weilOpenStrip_subset_closedStrip
#print axioms LeanLab.Riemann.one_sub_mem_weilOpenStrip_iff
#print axioms LeanLab.Riemann.one_sub_mem_weilClosedStrip_iff
#print axioms LeanLab.Riemann.conj_mem_weilOpenStrip_iff
#print axioms LeanLab.Riemann.conj_mem_weilClosedStrip_iff
#print axioms LeanLab.Riemann.one_sub_conj_mem_weilOpenStrip_iff
#print axioms LeanLab.Riemann.one_sub_conj_mem_weilClosedStrip_iff
#print axioms LeanLab.Riemann.isWeilStripAdmissible_zero
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.add
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.const_smul
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.weilInvolution
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.conj
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.weilStar
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.weilConvolution
#print axioms LeanLab.Riemann.IsWeilStripAdmissible.weilAutocorrelation
#print axioms LeanLab.Riemann.differentiableAt_GammaR_of_re_pos
#print axioms LeanLab.Riemann.logDeriv_riemannXiFactor
#print axioms LeanLab.Riemann.riemannXi_eq_factor_mul_GammaR_mul_riemannZeta
#print axioms LeanLab.Riemann.logDeriv_riemannZeta_eq_neg_vonMangoldtLSeries
#print axioms LeanLab.Riemann.logDeriv_riemannXi_eq_poles_archimedean_sub_vonMangoldt
#print axioms LeanLab.Riemann.exists_weilExplicitIntegrand_eq_hadamardZeroSum
#print axioms LeanLab.Riemann.summableLocallyUniformlyOn_riemannXiLogDerivZeroTerm
#print axioms LeanLab.Riemann.finite_riemannXiZeroStrictlyInsideRectangle
#print axioms LeanLab.Riemann.rectangleBoundaryIntegral_weighted_cauchyKernel
#print axioms LeanLab.Riemann.hasSum_rectangleBoundaryIntegral_weighted_riemannXiLogDerivZeroTerm
#print axioms LeanLab.Riemann.rectangleBoundaryIntegral_weighted_riemannXiLogDerivZeroTerm
#print axioms LeanLab.Riemann.rectangleBoundaryIntegral_weighted_riemannXiZeroSum_eq_finsum
#print axioms LeanLab.Riemann.rectangleBoundaryIntegral_weighted_logDeriv_riemannXi_eq_finsum
#print axioms LeanLab.Riemann.summable_riemannXiGaussianWeight
#print axioms LeanLab.Riemann.gaussianXiSelectedHeight_zeroFreeBoundary
#print axioms LeanLab.Riemann.tendsto_gaussianXiTopHorizontalIntegral
#print axioms LeanLab.Riemann.tendsto_gaussianXiRightVerticalIntegral
#print axioms LeanLab.Riemann.exists_gaussianXiZeroFreeHeight_tendsto_rightVerticalIntegral
#print axioms LeanLab.Riemann.integral_gaussianXiPrimeLineTerm
#print axioms LeanLab.Riemann.hasSum_integral_gaussianXiPrimeLineTerm
#print axioms LeanLab.Riemann.integrable_gaussianXiArchimedean
#print axioms LeanLab.Riemann.integral_gaussianXiPolePair_eq
#print axioms LeanLab.Riemann.gaussianXi_arithmetic_explicit_formula
#print axioms LeanLab.Riemann.tendsto_selectedXiRightVerticalIntegralFor
#print axioms LeanLab.Riemann.integral_shiftedGaussianXiPrimeLineTerm
#print axioms LeanLab.Riemann.summable_symmetricGaussianVonMangoldtWeight
#print axioms LeanLab.Riemann.integral_symmetricGaussianXiPolePair_eq
#print axioms LeanLab.Riemann.symmetricGaussianXi_arithmetic_explicit_formula
#print axioms LeanLab.Riemann.symmetricGaussianXi_arithmetic_explicit_formula_zero
#print axioms LeanLab.Riemann.summable_riemannXiSymmetricGaussianPacketWeight
#print axioms LeanLab.Riemann.summable_symmetricGaussianPacketVonMangoldtWeight
#print axioms LeanLab.Riemann.integrable_symmetricGaussianXiPacketArchimedean
#print axioms LeanLab.Riemann.symmetricGaussianXiPacket_arithmetic_explicit_formula
#print axioms LeanLab.Riemann.symmetricGaussianXiPacket_arithmetic_explicit_formula_unit
#print axioms LeanLab.Riemann.symmetricGaussianXiPacket_arithmetic_explicit_formula_empty
#print axioms LeanLab.Riemann.RiemannHypothesis.riemannXiSymmetricGaussianWeight_on_criticalLine
#print axioms LeanLab.Riemann.gaussianWeil_sum_mul_cos_sub_eq_sq_add_sq
#print axioms LeanLab.Riemann.RiemannHypothesis.summable_gaussianXiZeroSquareTerm
#print axioms LeanLab.Riemann.RiemannHypothesis.gaussianXiZeroQuadratic_eq_tsum_square
#print axioms LeanLab.Riemann.gaussianXiZeroQuadratic_arithmetic_formula
#print axioms LeanLab.Riemann.RiemannHypothesis.gaussianXiArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.gaussianXiArithmeticQuadratic_zero
#print axioms LeanLab.Riemann.gaussianCriterion_exists_pos_exp_mul_separates_finsets
#print axioms LeanLab.Riemann.gaussianCriterion_tendsto_tsum_gaussianScaledHigherTerm_zero
#print axioms LeanLab.Riemann.gaussianCriterion_exists_pos_tsum_gaussianGeneratedPacket_re_neg_of_offLine
#print axioms LeanLab.Riemann.gaussianCriterion_exists_pos_gaussianXiArithmeticQuadratic_re_neg_of_offLine
#print axioms LeanLab.Riemann.riemannHypothesis_of_gaussianXiArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.riemannHypothesis_iff_gaussianXiArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.fixedWidth_tendsto_cosh_pow_exp
#print axioms LeanLab.Riemann.fixedWidth_tendsto_gaussianXiZeroQuadratic_tensor_width
#print axioms LeanLab.Riemann.fixedWidth_exists_gt_gaussianXiArithmeticQuadratic_re_neg_of_offLine
#print axioms LeanLab.Riemann.riemannHypothesis_of_fixedWidth_gaussianXiArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.riemannHypothesis_iff_fixedWidth_gaussianXiArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.compactLaplaceTransform_additiveConvolution
#print axioms LeanLab.Riemann.norm_compactLaplaceTransform_le_mass_mul_inv_sq
#print axioms LeanLab.Riemann.summable_norm_compactLaplaceTransform_xiDivisorZero
#print axioms LeanLab.Riemann.compactLaplaceTransform_polynomialPacket
#print axioms LeanLab.Riemann.exists_compactSupport_xiDivisor_laplace_tsum_separator
#print axioms LeanLab.Riemann.differentiable_compactLaplaceTransform
#print axioms LeanLab.Riemann.compactLaplaceTransform_iterate_deriv
#print axioms LeanLab.Riemann.norm_compactLaplaceTransform_le_mass_mul_inv_pow_six
#print axioms LeanLab.Riemann.tendsto_symmetrizedCompactLaplaceTopHorizontalIntegral
#print axioms LeanLab.Riemann.tendsto_symmetrizedCompactLaplaceXiRightVerticalIntegral
#print axioms LeanLab.Riemann.integral_compactSymmetrizedXiPrimeLineTerm
#print axioms LeanLab.Riemann.hasFiniteSupport_compactSymmetrizedVonMangoldtWeight
#print axioms LeanLab.Riemann.integral_compactSymmetrizedXiPolePair_eq
#print axioms LeanLab.Riemann.integrable_compactSymmetrizedXiArchimedean
#print axioms LeanLab.Riemann.symmetrizedCompactLaplaceXi_arithmetic_explicit_formula
#print axioms LeanLab.Riemann.compactLaplaceTransform_iterate_deriv_of_le_six
#print axioms LeanLab.Riemann.integrable_fourier_compactLaplaceDensity_of_sixContDiff
#print axioms LeanLab.Riemann.integrable_abs_mul_norm_fourier_compactLaplaceDensity
#print axioms LeanLab.Riemann.tendsto_symmetrizedCompactLaplaceXiRightVerticalIntegral_sixContDiff
#print axioms LeanLab.Riemann.symmetrizedCompactLaplaceXi_arithmetic_explicit_formula_sixContDiff
#print axioms LeanLab.Riemann.riemannXi_conj
#print axioms LeanLab.Riemann.compactLaplaceTransform_conjInvolution
#print axioms LeanLab.Riemann.exists_compactSupport_xiDivisor_laplace_tsum_separator_vanishesOn
#print axioms LeanLab.Riemann.compactWeilZeroQuadratic_eq_rawZeroQuadratic
#print axioms LeanLab.Riemann.exists_compactWeilArithmeticQuadratic_re_neg_of_offLine
#print axioms LeanLab.Riemann.riemannHypothesis_iff_compactWeilArithmeticQuadratic_re_nonneg
#print axioms LeanLab.Riemann.symmetricGaussianVonMangoldtWeight_eq_ofReal_kernel
#print axioms LeanLab.Riemann.symmetricGaussianVonMangoldtWeight_audit_offDiag_gt_diag
#print axioms LeanLab.Riemann.not_posSemidef_symmetricGaussianPrimeKernelMatrix_audit
#print axioms LeanLab.Riemann.exists_pos_symmetricGaussianPrimeKernelMatrix_indefinite
#print axioms LeanLab.Riemann.polsonImaginaryFrullaniComponent_eq_ofReal
#print axioms LeanLab.Riemann.not_integrableOn_polsonImaginaryFrullaniIntegrand
#print axioms LeanLab.Riemann.not_integrableOn_polsonImaginaryFrullaniComponent
#print axioms LeanLab.Riemann.freedmanGreenLift_listedPremises_do_not_force_contraction
#print axioms LeanLab.Riemann.contraction_comp_three
#print axioms LeanLab.Riemann.integral_fractionalPartKernel_mul_le
#print axioms LeanLab.Riemann.baezDuarteNormalizedKernel_diagonal_lower
#print axioms LeanLab.Riemann.norm_inner_sparseGram_ne_le
#print axioms LeanLab.Riemann.sparseGram_lower_frame_bound
#print axioms LeanLab.Riemann.finiteGramWitness_posDef
#print axioms LeanLab.Riemann.finiteGramWitness_target_orthogonal
#print axioms LeanLab.Riemann.inner_baezDuarteKernelL2_sparseTargetWitnessRealL2_eq_zero
#print axioms LeanLab.Riemann.inner_target_sparseTargetWitness
#print axioms LeanLab.Riemann.baezDuarteComplexTargetL2_not_mem_sparseGramKernelClosure
#print axioms LeanLab.Riemann.mellin_hurwitzEvenFEPair_zero_critical_line
#print axioms LeanLab.Riemann.completedRiemannZeta₀_critical_line_eq_thetaTailIntegral
#print axioms LeanLab.Riemann.integral_Ioi_deBruijnNewmanPhi_mul_cos
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_eq_riemannXi
#print axioms LeanLab.Riemann.integrableOn_one_add_sq_mul_exp_mul_norm_deBruijnNewmanPhi
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewmanH_time
#print axioms LeanLab.Riemann.differentiable_deBruijnNewmanH
#print axioms LeanLab.Riemann.deriv_deriv_deBruijnNewmanH
#print axioms LeanLab.Riemann.deBruijnNewmanH_backward_heat_equation
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_iff_isNontrivialZero
#print axioms LeanLab.Riemann.deBruijnNewmanH_zeroCoordinate_eq_zero_iff
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_im_mem_Ioo
#print axioms LeanLab.Riemann.riemannHypothesis_iff_deBruijnNewmanAllZerosReal_zero
#print axioms LeanLab.Riemann.deBruijnNewman_zeroCoordinate_framework
#print axioms LeanLab.Riemann.deBruijnNewmanPhi_pos
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_ne_zero
#print axioms LeanLab.Riemann.continuous_deBruijnNewmanH_joint
#print axioms LeanLab.Riemann.isClosed_setOf_deBruijnNewmanAllZerosReal
#print axioms LeanLab.Riemann.deBruijnNewmanH_entireOfOrderAtMost_one
#print axioms LeanLab.Riemann.exists_deBruijnNewmanH_constant_hadamard_factorization
#print axioms LeanLab.Riemann.deBruijnNewman_verticalAverage_allZerosReal
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_mono
#print axioms LeanLab.Riemann.deBruijnNewmanH_conj
#print axioms LeanLab.Riemann.analyticOrderNatAt_conj_eq
#print axioms LeanLab.Riemann.norm_weierstrassFactor_pair_sub_I_lt_add_I
#print axioms LeanLab.Riemann.verticalAverage_zero_im_sq_le
#print axioms LeanLab.Riemann.dbnCoshApprox_zero_im_sq_le
#print axioms LeanLab.Riemann.eventually_exists_dbnForwardApprox_zero_mem_closedBall
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_im_sq_le_one_sub_two_mul
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_one_half
#print axioms LeanLab.Riemann.continuous_deBruijnNewmanHSecondMoment_joint
#print axioms LeanLab.Riemann.summable_deBruijnNewman_regularizedZeroForceTerm
#print axioms LeanLab.Riemann.deBruijnNewmanH_second_deriv_div_two_deriv_eq_regularizedZeroForce
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewmanH_along
#print axioms LeanLab.Riemann.deBruijnNewman_simpleZeroPath_velocity
#print axioms LeanLab.Riemann.deBruijnNewman_simpleZeroPath_velocity_of_eventually
#print axioms LeanLab.Riemann.exists_deBruijnNewman_localRealSimpleZeroPath
#print axioms LeanLab.Riemann.exists_deBruijnNewman_orderedLocalRealSimpleZeroPaths
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewman_simpleZeroPath_realGapSq
#print axioms LeanLab.Riemann.summable_deBruijnNewman_zeroPairForceTerm
#print axioms LeanLab.Riemann.deBruijnNewmanRegularizedZeroForce_sub_eq_two_div_add_pairRemainder
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewman_simpleZeroPath_realGapSq_pairRemainder
#print axioms LeanLab.Riemann.deBruijnNewmanH_divisorZeroIndex₀_val_eq_zero
#print axioms LeanLab.Riemann.realPairForceContribution_re_pos_of_between
#print axioms LeanLab.Riemann.deBruijnNewmanZeroPairForceRemainder_re_nonpos
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewman_adjacentSimpleZeroPath_realGapSq_and_deriv_le_eight
#print axioms LeanLab.Riemann.deBruijnNewman_adjacentSimpleZeroPath_realGapSq_lower_bound
#print axioms LeanLab.Riemann.h6GapAuditHeatPolynomial_backwardHeatEquation
#print axioms LeanLab.Riemann.exists_h6GapAuditHeatPolynomial_collision_within
#print axioms LeanLab.Riemann.norm_le_of_forall_norm_finiteComplexPowerSum_le
#print axioms LeanLab.Riemann.norm_eq_sqrt_of_powerSum_bound_and_reciprocal
#print axioms LeanLab.Riemann.h6AuditHeatXiQuadratic_one_allZerosOnCriticalLine
#print axioms LeanLab.Riemann.h6AuditSecondLiValue_zero
#print axioms LeanLab.Riemann.h6AuditSecondLiValue_one
#print axioms LeanLab.Riemann.h6AuditHeatXiQuadratic_falsifies_reverseLiTransfer
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_one_sub
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_zero_eq_riemannXi
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_heat_equation
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiOne_eq
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiMomentB_sq_le_mul
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiTwo_eq
#print axioms LeanLab.Riemann.deBruijnNewmanHeat_firstTwoLi_endpoint
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiMomentD_pos
#print axioms LeanLab.Riemann.deriv_deriv_deriv_deBruijnNewmanHeatXi_one_eq
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiMomentB_mul_C_le_A_mul_D
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiThree_eq
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiThree_zero_eq_candidate_two
#print axioms LeanLab.Riemann.liCoefficientCandidate_two_re_pos
#print axioms LeanLab.Riemann.deBruijnNewmanHeat_thirdLi_covariance_endpoint
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_entireOfOrderAtMost_one
#print axioms LeanLab.Riemann.all_values_on_line_iff_forall_coefficient_re_nonneg
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiCoefficient_eq_tsum_pairedLiZeroTerm
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_iff_forall_heatLiCoefficient_re_nonneg
#print axioms LeanLab.Riemann.deBruijnNewmanHeatLiCoefficient_zero_eq
#print axioms LeanLab.Riemann.riemannHypothesis_iff_forall_deBruijnNewmanHeatLiCoefficient_zero_re_nonneg
#print axioms LeanLab.Riemann.deBruijnNewmanHeat_allIndexLi_endpoint
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_timeRatio_eq_spaceSecondRatio
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_spaceSecondRatio_eq_logDeriv_evolution
#print axioms LeanLab.Riemann.deBruijnNewmanHeatXi_timeRatio_eq_logDeriv_evolution
#print axioms LeanLab.Riemann.forall_heatLiCoefficient_zero_re_nonneg_of_atBot_zero_and_monotone
#print axioms LeanLab.Riemann.riemannHypothesis_of_heatLi_atBot_zero_and_monotone_assumptions
#print axioms LeanLab.Riemann.h6PositiveCoshAudit_entire
#print axioms LeanLab.Riemann.h6PositiveCoshAudit_coefficients_pos
#print axioms LeanLab.Riemann.h6PositiveCoshAuditLiThree_eq
#print axioms LeanLab.Riemann.h6PositiveCoshAuditLiThree_re_neg
#print axioms LeanLab.Riemann.h6PositiveCoshAudit_falsifies_allOrder_positiveKernelLi
#print axioms LeanLab.Riemann.xiLogConcavityAudit_isLogConcaveOn_trivial
#print axioms LeanLab.Riemann.not_xiLogConcavityAuditHurwitzSchema
#print axioms LeanLab.Riemann.xiKernelLogConcavityExternalAudit_endpoint
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewmanPhi
#print axioms LeanLab.Riemann.hasDerivAt_deBruijnNewmanPhiDeriv
#print axioms LeanLab.Riemann.deBruijnNewmanPhiSecond_mul_phi_sub_deriv_sq_neg
#print axioms LeanLab.Riemann.pf5_phi_bounds
#print axioms LeanLab.Riemann.xiKernelPF5CenterMatrix_det_lt
#print axioms LeanLab.Riemann.xiKernelPF5ToeplitzMatrix_det_neg
#print axioms LeanLab.Riemann.not_isPolyaFrequencyFive_deBruijnNewmanEvenKernel
#print axioms LeanLab.Riemann.dbnCoshApprox_zero_im_sq_le_of
#print axioms LeanLab.Riemann.dbnForwardApprox_zero_im_sq_le_of
#print axioms LeanLab.Riemann.eventually_exists_dbnForwardApprox_zero_mem_closedBall_of
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_im_sq_le_sub_two_mul
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_add_half_sq
#print axioms LeanLab.Riemann.eventually_exists_deBruijnNewmanH_zero_mem_closedBall
#print axioms LeanLab.Riemann.exists_deBruijnNewmanH_isolating_closedBall_subset
#print axioms LeanLab.Riemann.exists_deBruijnNewman_localComplexSimpleZeroPath
#print axioms LeanLab.Riemann.deBruijnNewmanH_mul_I_re_pos
#print axioms LeanLab.Riemann.exists_deBruijnNewmanPolymath_firstBadTime
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_im_eq_boundary
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_not_simple_of_force_lt
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_not_backwardUpperLinearEscape
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_repeated_obstruction_of_force_lt
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_add_half_sq_of_im_abs_lt
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_one_fifth_of_polymath_table_endpoint
#print axioms LeanLab.Riemann.analyticOrderNatAt_neg_eq
#print axioms LeanLab.Riemann.divisorZeroIndexNegEquiv_val
#print axioms LeanLab.Riemann.deBruijnNewmanRegularizedZeroForce_eq_divisor_tsum
#print axioms LeanLab.Riemann.tsum_eq_quarter_tsum_equiv_orbit
#print axioms LeanLab.Riemann.deBruijnNewmanRegularizedZeroForce_eq_quarter_orbit_tsum
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathForceOrbitTerm_im_nonpos_of_escape
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathForceOrbitTerm_eq_of_value_eq_contact
#print axioms LeanLab.Riemann.deBruijnNewman_simpleZero_fiber_card_eq_one
#print axioms LeanLab.Riemann.exists_deBruijnNewmanHDivisorZeroIndex_value_eq_abs_cartesian
#print axioms LeanLab.Riemann.deBruijnNewmanHDivisorZeroSymmetryOrbit_card_eq_four_of_contact
#print axioms LeanLab.Riemann.deBruijnNewmanRegularizedZeroForce_im_lt_of_simple_contact_escape
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_horizontal_escape
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_force_lt_of_simple_contact
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_firstBadWitness_not_simple
#print axioms LeanLab.Riemann.deBruijnNewmanBackwardHermite_comp_neg_X
#print axioms LeanLab.Riemann.deBruijnNewmanBackwardHermite_eval_ne_zero_of_ne_zero
#print axioms LeanLab.Riemann.exists_deBruijnNewmanBackwardHermite_aeval_eq_zero_im_pos
#print axioms LeanLab.Riemann.exists_deBruijnNewmanH_repeated_zero_entire_factor
#print axioms LeanLab.Riemann.integrable_deBruijnNewmanH_gaussian_shift_kernel
#print axioms LeanLab.Riemann.integral_deBruijnNewmanH_gaussian_shift
#print axioms LeanLab.Riemann.exists_deBruijnNewmanH_repeated_zero_gaussian_scaling
#print axioms LeanLab.Riemann.iteratedDeriv_cexp_mul_add_sq_eq_deBruijnNewmanBackwardHermite
#print axioms LeanLab.Riemann.integral_add_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite
#print axioms LeanLab.Riemann.continuousAt_deBruijnNewman_gaussian_scaled_factor_integral
#print axioms LeanLab.Riemann.tendsto_deBruijnNewman_gaussian_scaled_factor_integral
#print axioms LeanLab.Riemann.tendstoUniformlyOn_deBruijnNewman_gaussian_scaled_factor_integral
#print axioms LeanLab.Riemann.eventually_exists_gaussian_scaled_factor_integral_zero_upper
#print axioms LeanLab.Riemann.deBruijnNewmanHasBackwardUpperLinearEscape_of_repeated
#print axioms LeanLab.Riemann.deBruijnNewmanH_zero_im_abs_lt_of_polymath_regions
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_add_half_sq_of_polymath_regions
#print axioms LeanLab.Riemann.deBruijnNewmanAllZerosReal_one_fifth_of_polymath_table_row
#print axioms LeanLab.Riemann.RiemannHypothesis.riemannHypothesisUpTo
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathInitialRegionZeroFree_of_riemannHypothesisUpTo
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathInitialRegionZeroFree_table_row_of_rh_up_to_three_trillion

#print axioms LeanLab.Riemann.deBruijnNewmanPolymathLogM0_hasDerivAt
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathAlpha_eq_compact
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_exp_logM0_eq_M0
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathB_ne_zero
#print axioms LeanLab.Riemann.deBruijnNewmanPolymath_table_row_final_mem_effectiveRegion
#print axioms LeanLab.Riemann.deBruijnNewmanH_ne_zero_of_polymathExplicitCertificate
#print axioms LeanLab.Riemann.deBruijnNewmanPolymathFinalRegionZeroFree_table_row_of_explicitCertificates
#print axioms LeanLab.Riemann.integral_complex_cos_imaginary_gaussian_shift
#print axioms LeanLab.Riemann.integrable_deBruijnNewmanH_imaginary_gaussian_shift_kernel
#print axioms LeanLab.Riemann.integral_deBruijnNewmanH_imaginary_gaussian_shift
#print axioms LeanLab.Riemann.deBruijnNewmanH_eq_gaussian_zero_imaginary_shift
#print axioms LeanLab.Riemann.deBruijnNewmanH_eq_gaussian_riemannXi
#print axioms LeanLab.Riemann.deBruijnNewmanRiemannSiegelDirection_sq
#print axioms LeanLab.Riemann.two_le_norm_deBruijnNewmanRiemannSiegelDenominator
#print axioms LeanLab.Riemann.integrable_deBruijnNewmanRiemannSiegelLineIntegrand
#print axioms LeanLab.Riemann.deBruijnNewmanRiemannSiegelKernel_hasResidue
#print axioms LeanLab.Riemann.deBruijnNewmanRiemannSiegelContour_prefix
