import LeanLab.Riemann.BalazardSaias
import LeanLab.Riemann.LiZeroDivisor
import LeanLab.Riemann.LiHadamard
import LeanLab.Riemann.LiZeroFormula
import LeanLab.Riemann.LiSymmetricZeroFormula
import LeanLab.Riemann.LiReverseCriterion
import LeanLab.Riemann.WeilTestAlgebra
import LeanLab.Riemann.WeilConvolution
import LeanLab.Riemann.AnalyticLogBranch
import LeanLab.Riemann.ReciprocalZetaSubpower
import LeanLab.Riemann.TruncatedPerron
import LeanLab.Riemann.BalazardSaiasContour
import LeanLab.Riemann.BaezDuarteReverse
import LeanLab.Riemann.BaezDuarteForward
import LeanLab.Riemann.BaezDuarteForwardLimit
import LeanLab.Riemann.BurnolLowerBound
import LeanLab.Riemann.BurnolA
import LeanLab.Riemann.BurnolHardy
import LeanLab.Riemann.BurnolY
import LeanLab.Riemann.BurnolGram
import LeanLab.Riemann.BurnolFiniteLowerBound
import LeanLab.Riemann.BurnolFullLowerBound
import LeanLab.Riemann.M2ProjectionNormAudit
import LeanLab.Riemann.M2LadderFrequencyAudit
import LeanLab.Riemann.M2GramGeometry
import LeanLab.Riemann.M2SparseObstruction

set_option linter.style.header false
set_option linter.style.longLine false

/-!
# Trusted-dependency audit for fixed-gap RH work

The build log for this module must list only Lean's standard extensionality, choice, and quotient
principles for each theorem below.
-/

#print axioms riemannZeta_eq_zetaAbelContinuationFormula
#print axioms LeanLab.Riemann.riemannZeta_eq_zetaAbelContinuationFormula_of_re_pos
#print axioms LeanLab.Riemann.hasMellin_fractionalPartKernel_one
#print axioms LeanLab.Riemann.hasMellin_baezDuarteKernel
#print axioms LeanLab.Riemann.expNeg_quasiMeasurePreserving
#print axioms LeanLab.Riemann.eLpNorm_weightedLogForwardFun
#print axioms LeanLab.Riemann.weightedLogForward_inverse
#print axioms LeanLab.Riemann.weightedLogPullback_coeFn
#print axioms LeanLab.Riemann.weightedLogPullback_symm_coeFn
#print axioms LeanLab.Riemann.norm_baezDuarteFourierMellinL2
#print axioms LeanLab.Riemann.mellin_criticalLine_eq_fourier
#print axioms LeanLab.Riemann.baezDuarteVerticalMajorant_memLp
#print axioms LeanLab.Riemann.baezDuarteCriticalLineZetaZeroOrdinates_countable
#print axioms LeanLab.Riemann.ae_tendsto_baezDuarteZetaRatio_one
#print axioms LeanLab.Riemann.baezDuarteMobiusApprox_two_mul_eq_dirichletTail_of_one_lt
#print axioms LeanLab.Riemann.baezDuarte_weightedTail_norm_sq_le
#print axioms LeanLab.Riemann.tendsto_norm_zero_of_baezDuarte_weightedTail
#print axioms LeanLab.Riemann.baezDuarte_finsupp_norm_sq_le_of_weighted
#print axioms Complex.exists_norm_digamma_le_log
#print axioms LeanLab.Riemann.exists_norm_Gamma_div_le_rpow_of_re_mem_Icc
#print axioms LeanLab.Riemann.exists_norm_baezDuarteZetaRatio_le_rpow
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatio_bound
#print axioms LeanLab.Riemann.exists_baezDuarteZetaRatioIntegrand_majorant
#print axioms LeanLab.Riemann.differentiable_zetaPoleRemoved
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.norm_Gamma_mul_cos_one_sub_mul_I_le
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_one_add_mul_I_le_rpow
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_mul_I_le_rpow
#print axioms Complex.zeta_minus_pole_entire_growth
#print axioms LeanLab.Riemann.fioriMidpointQuotient_zetaPoleRemoved_growth
#print axioms LeanLab.Riemann.exists_norm_zetaPoleRemoved_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_criticalLine_le_rpow
#print axioms LeanLab.Riemann.exists_norm_riemannZeta_div_criticalLine_le_rpow
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le
#print axioms LeanLab.Riemann.burnolMobiusMajorant_memLp
#print axioms LeanLab.Riemann.tendsto_natCast_rpow_neg_delta_div_three
#print axioms Complex.exists_differentiableOn_eqOn_exp_comp_of_isSimplyConnected
#print axioms LeanLab.Riemann.exists_riemannZeta_differentiableLogBranch
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_reciprocalZeta_subpower_bound
#print axioms LeanLab.Riemann.LSeries_moebius_eq_reciprocal_riemannZeta
#print axioms LeanLab.Riemann.norm_perronIntegrand_vertical_integral_le_of_neg
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_le_of_lt_one
#print axioms LeanLab.Riemann.integral_inv_boundary_rect_eq_two_pi_mul_I
#print axioms LeanLab.Riemann.norm_truncatedPerronKernel_two_sub_one_le_of_one_lt
#print axioms LeanLab.Riemann.hasSum_integral_mobiusPerronSeriesTerm
#print axioms LeanLab.Riemann.exists_mobiusDirichletPartialSum_sub_truncatedPerronIntegral_le
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_balazardSaias_specialized_bound_compiled
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_norm_burnolMobiusTransformedError_le_compiled
#print axioms LeanLab.Riemann.riemannZeta_ne_zero_of_baezDuarteComplexTarget_mem_closure
#print axioms LeanLab.Riemann.baezDuarteComplexTarget_mem_closure_imp_riemannHypothesis
#print axioms LeanLab.Riemann.fourier_toLp_eq_toLp_fourier
#print axioms LeanLab.Riemann.RiemannHypothesis.cauchySeq_baezDuarteMobiusApproxComplexL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_baezDuarteMobiusApproxL2
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_weightedMobiusTransformedError_majorant
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_tendsto_scaledWeightedLimitTransform_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.exists_mobiusApproxL2_close_neg_target
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteComplexTargetL2_mem_kernelClosure
#print axioms LeanLab.Riemann.riemannHypothesis_iff_baezDuarteComplexTarget_mem_kernelClosure
#print axioms LeanLab.Riemann.baezDuarteFiniteComplexKernelSpan_le_burnolKernelSpan
#print axioms LeanLab.Riemann.burnolDistance_inv_natCast_le_baezDuarteNaturalDistance
#print axioms LeanLab.Riemann.tendsto_natCast_inv_nhdsWithin_Ioi_zero
#print axioms LeanLab.Riemann.burnolA_eq_tailIntegral_sub_fractionalPart
#print axioms LeanLab.Riemann.burnolA_memLp_two_positiveHalfLine
#print axioms LeanLab.Riemann.mellin_burnolComplexFractionalPartTail_eq
#print axioms LeanLab.Riemann.hasMellin_burnolA
#print axioms LeanLab.Riemann.norm_burnolHardyInverseMultiplier
#print axioms LeanLab.Riemann.hasMellin_burnolChiOne
#print axioms LeanLab.Riemann.burnolHardyInverseL2_target
#print axioms LeanLab.Riemann.burnolHardyInverseL2_kernel
#print axioms LeanLab.Riemann.burnolHardyInverseL2_map_kernelSpan
#print axioms LeanLab.Riemann.burnolDistance_eq_modelDistance
#print axioms LeanLab.Riemann.ae_burnolAPhaseMultiplier_eq_source
#print axioms LeanLab.Riemann.burnolAPhaseL2_burnolPsiL2_eq_hardySquare
#print axioms LeanLab.Riemann.tendsto_burnolPreY
#print axioms LeanLab.Riemann.burnolAPhaseL2_burnolY_coeFn
#print axioms LeanLab.Riemann.norm_burnolYTransformed_sub_V_cpow_le
#print axioms LeanLab.Riemann.norm_burnolYTransformed_le_large
#print axioms LeanLab.Riemann.inner_burnolY_normalizedModelKernel
#print axioms LeanLab.Riemann.burnolY_mem_modelKernelSpan_orthogonal
#print axioms LeanLab.Riemann.tendsto_inner_burnolX
#print axioms LeanLab.Riemann.burnolChiOnePhase_isBigO_sq
#print axioms LeanLab.Riemann.burnolAPhaseL2_chiOne
#print axioms LeanLab.Riemann.tendsto_sqrtLog_inner_chiOne_burnolX
#print axioms LeanLab.Riemann.burnolHilbertMatrix_isUnit_det
#print axioms LeanLab.Riemann.burnolHilbertMatrix_inv_zero_zero
#print axioms LeanLab.Riemann.tendsto_burnolGramMatrix_inv
#print axioms LeanLab.Riemann.tendsto_burnolBlockGramMatrix
#print axioms LeanLab.Riemann.tendsto_burnolBlockGramMatrix_inv
#print axioms LeanLab.Riemann.tendsto_burnolFiniteGramMatrix
#print axioms LeanLab.Riemann.burnolFiniteHilbertMatrix_isUnit_det
#print axioms LeanLab.Riemann.tendsto_burnolFiniteGramMatrix_inv
#print axioms LeanLab.Riemann.analyticOrderAt_riemannZeta_ne_top_of_isNontrivialZero
#print axioms LeanLab.Riemann.norm_burnolFiniteZetaProjection_le_distance
#print axioms LeanLab.Riemann.RiemannHypothesis.burnolDistance_liminf_ge_finset
#print axioms LeanLab.Riemann.RiemannHypothesis.burnolDistance_liminf_ge_fullZeroSum
#print axioms LeanLab.Riemann.RiemannHypothesis.baezDuarteNaturalDistance_liminf_ge_fullZeroSum
#print axioms LeanLab.Riemann.exists_symmetric_idempotent_not_maxNorm_nonexpansive
#print axioms LeanLab.Riemann.not_m2AuditWongPThree_maxNorm_nonexpansive
#print axioms LeanLab.Riemann.not_m2Audit_carvill_source_frequency_lower_bound
#print axioms LeanLab.Riemann.riemannXi_ne_zero_of_isTrivialZeroPoint
#print axioms LeanLab.Riemann.isNontrivialZero_iff_riemannXi_eq_zero
#print axioms LeanLab.Riemann.analyticOrderAt_riemannXi_ne_top
#print axioms LeanLab.Riemann.riemannXiZeroDivisor_apply
#print axioms LeanLab.Riemann.support_riemannXiZeroDivisor
#print axioms LeanLab.Riemann.riemannXiZeroMultiplicity_one_sub
#print axioms LeanLab.Riemann.riemannXi_eq_complex_riemannXi
#print axioms LeanLab.Riemann.riemannXi_divisor_toNat_eq_zeroMultiplicity
#print axioms LeanLab.Riemann.exists_riemannXiDivisorZeroIndex_val_iff
#print axioms LeanLab.Riemann.riemannXi_entireOfOrderAtMost_one
#print axioms LeanLab.Riemann.summable_riemannXiDivisorZeroIndex_norm_inv_sq
#print axioms LeanLab.Riemann.exists_riemannXi_hadamard_factorization
#print axioms LeanLab.Riemann.exists_riemannXi_logDeriv_eq_polynomial_derivative_add_tsum
#print axioms LeanLab.Riemann.summableLocallyUniformlyOn_riemannXiLogDerivZeroDerivativeTerm
#print axioms LeanLab.Riemann.iteratedDeriv_tsum_riemannXiLogDerivZeroTerm
#print axioms LeanLab.Riemann.liCoefficientCandidate_eq_finset_sum_iteratedDeriv_logDeriv
#print axioms LeanLab.Riemann.iteratedDeriv_logDeriv_riemannXi_eq_hadamard_zero_formula
#print axioms LeanLab.Riemann.exists_liCoefficientCandidate_eq_hadamard_zero_formula
#print axioms LeanLab.Riemann.not_summable_liRawZeroTerm_one_nat_succ
#print axioms LeanLab.Riemann.liRawZeroTerm_pair_quarter_two
#print axioms LeanLab.Riemann.riemannXiDivisorZeroReflectEquiv
#print axioms LeanLab.Riemann.summable_riemannXiSymmetrizedLiZeroTerm
#print axioms LeanLab.Riemann.liCoefficientCandidate_eq_tsum_riemannXiSymmetrizedLiZeroTerm
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_eq_tsum_normSq
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_im_eq_zero
#print axioms LeanLab.Riemann.RiemannHypothesis.liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.exists_even_gt_forall_circle_pow_dist_one_lt
#print axioms LeanLab.Riemann.norm_liZeroTransform_le_one_iff
#print axioms LeanLab.Riemann.finite_riemannXiLiOrbitRadius_superlevel
#print axioms LeanLab.Riemann.norm_tsum_indicator_compl_riemannXiSymmetrizedLiZeroTerm_le
#print axioms LeanLab.Riemann.three_quarters_mul_orbitRadius_pow_lt_dominant_pow_re
#print axioms LeanLab.Riemann.exists_liCoefficientCandidate_re_neg_of_divisorZero_re_ne_half
#print axioms LeanLab.Riemann.riemannHypothesis_of_forall_liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.riemannHypothesis_iff_forall_liCoefficientCandidate_re_nonneg
#print axioms LeanLab.Riemann.weilInvolution_involution_of_pos
#print axioms LeanLab.Riemann.weilInvolution_involution_not_at_zero
#print axioms LeanLab.Riemann.mellinConvergent_weilInvolution_iff
#print axioms LeanLab.Riemann.mellin_weilInvolution
#print axioms LeanLab.Riemann.mellin_weilInvolution_zero
#print axioms LeanLab.Riemann.mellin_weilInvolution_one
#print axioms LeanLab.Riemann.mellin_conj
#print axioms LeanLab.Riemann.mellinConvergent_conj_iff
#print axioms LeanLab.Riemann.mellin_weilStar
#print axioms LeanLab.Riemann.mellinConvergent_weilStar_iff
#print axioms LeanLab.Riemann.mellin_weilStar_criticalLine
#print axioms LeanLab.Riemann.mellinConvergent_iff_integrable_mellinLogLift
#print axioms LeanLab.Riemann.mellin_eq_integral_mellinLogLift
#print axioms LeanLab.Riemann.weilConvolution_exp_neg
#print axioms LeanLab.Riemann.mellinLogLift_weilConvolution
#print axioms LeanLab.Riemann.mellinConvergent_weilConvolution
#print axioms LeanLab.Riemann.mellin_weilConvolution
#print axioms LeanLab.Riemann.mellin_weilConvolution_star
#print axioms LeanLab.Riemann.mellin_weilConvolution_star_criticalLine
#print axioms LeanLab.Riemann.mellin_weilAutocorrelation_criticalLine
#print axioms LeanLab.Riemann.integral_fractionalPartKernel_mul_le
#print axioms LeanLab.Riemann.baezDuarteNormalizedKernel_diagonal_lower
#print axioms LeanLab.Riemann.norm_inner_sparseGram_ne_le
#print axioms LeanLab.Riemann.sparseGram_lower_frame_bound
#print axioms LeanLab.Riemann.finiteGramWitness_posDef
#print axioms LeanLab.Riemann.finiteGramWitness_target_orthogonal
#print axioms LeanLab.Riemann.inner_baezDuarteKernelL2_sparseTargetWitnessRealL2_eq_zero
#print axioms LeanLab.Riemann.inner_target_sparseTargetWitness
#print axioms LeanLab.Riemann.baezDuarteComplexTargetL2_not_mem_sparseGramKernelClosure
