import LeanLab.Riemann.DeBruijnNewmanDynamics
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Probability.Distributions.Gaussian.Real

set_option linter.style.header false

open scoped Uniformity

/-!
# Backward Hermite splitting for the de Bruijn-Newman heat family

This file develops the local polynomial and scaled-zero infrastructure for a multiple zero under
backward heat flow. The normalization follows `partial_t H = -partial_z^2 H`: the leading scaled
polynomial is generated by `P_(n+1) = X * P_n + 2 * P_n'`.
-/

open Complex Filter Real Set Topology

namespace LeanLab.Riemann

noncomputable section

open Polynomial

theorem analyticOnNhd_deBruijnNewmanH (t : ℝ) :
    AnalyticOnNhd ℂ (deBruijnNewmanH t) (Set.univ : Set ℂ) :=
  analyticOnNhd_univ_iff_differentiable.mpr (differentiable_deBruijnNewmanH t)

theorem analyticOrderAt_deBruijnNewmanH_ne_top (t : ℝ) (z : ℂ) :
    analyticOrderAt (deBruijnNewmanH t) z ≠ ⊤ := by
  intro htop
  have hlocal : deBruijnNewmanH t =ᶠ[nhds z] (0 : ℂ → ℂ) := by
    filter_upwards [analyticOrderAt_eq_top.mp htop] with w hw
    simpa using hw
  have hglobal : deBruijnNewmanH t = (0 : ℂ → ℂ) :=
    (analyticOnNhd_deBruijnNewmanH t).eq_of_eventuallyEq analyticOnNhd_const hlocal
  have hzero := congrFun hglobal 0
  exact deBruijnNewmanH_zero_ne_zero t (by simpa using hzero)

/-- A repeated source-family zero has finite analytic multiplicity at least two and an analytic
nonvanishing residual factor. This is the local input for the square-root heat scaling. -/
theorem exists_deBruijnNewmanH_repeated_zero_factor
    {t : ℝ} {z : ℂ} (hz : deBruijnNewmanH t z = 0)
    (hrepeated : deriv (deBruijnNewmanH t) z = 0) :
    ∃ (m : ℕ) (g : ℂ → ℂ), 2 ≤ m ∧ AnalyticAt ℂ g z ∧ g z ≠ 0 ∧
      deBruijnNewmanH t =ᶠ[nhds z] fun w ↦ (w - z) ^ m * g w := by
  have hanalytic : AnalyticAt ℂ (deBruijnNewmanH t) z :=
    (differentiable_deBruijnNewmanH t).analyticAt z
  have hfinite := analyticOrderAt_deBruijnNewmanH_ne_top t z
  let m := analyticOrderNatAt (deBruijnNewmanH t) z
  have horder : ((2 : ℕ) : ℕ∞) ≤ analyticOrderAt (deBruijnNewmanH t) z := by
    rw [natCast_le_analyticOrderAt_iff_iteratedDeriv_eq_zero hanalytic]
    intro i hi
    interval_cases i
    · simpa using hz
    · simpa [iteratedDeriv_one] using hrepeated
  have hm : 2 ≤ m := by
    have hcast := Nat.cast_analyticOrderNatAt hfinite
    rw [← hcast] at horder
    exact_mod_cast horder
  obtain ⟨g, hganalytic, hgzero, hfactor⟩ :=
    (hanalytic.analyticOrderNatAt_eq_iff hfinite).mp (show m = m from rfl)
  exact ⟨m, g, hm, hganalytic, hgzero, hfactor⟩

/-- A repeated source-family zero admits a global entire residual factor. The iterated divided
difference gives a canonical extension through the zero, so the factorization remains valid away
from the local Taylor neighborhood as well. -/
theorem exists_deBruijnNewmanH_repeated_zero_entire_factor
    {t : ℝ} {z : ℂ} (hz : deBruijnNewmanH t z = 0)
    (hrepeated : deriv (deBruijnNewmanH t) z = 0) :
    ∃ (m : ℕ) (g : ℂ → ℂ), 2 ≤ m ∧ Differentiable ℂ g ∧ g z ≠ 0 ∧
      ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w := by
  obtain ⟨p, hp⟩ : ∃ p : FormalMultilinearSeries ℂ ℂ ℂ,
      HasFPowerSeriesAt (deBruijnNewmanH t) p z :=
    (differentiable_deBruijnNewmanH t).analyticAt z
  have hpne : p ≠ 0 := by
    intro hpzero
    have hlocal : deBruijnNewmanH t =ᶠ[nhds z] (0 : ℂ → ℂ) := by
      filter_upwards [hp.locally_zero_iff.mpr hpzero] with w hw
      simpa using hw
    have hglobal : deBruijnNewmanH t = (0 : ℂ → ℂ) :=
      (analyticOnNhd_deBruijnNewmanH t).eq_of_eventuallyEq analyticOnNhd_const hlocal
    have hzero := congrFun hglobal 0
    exact deBruijnNewmanH_zero_ne_zero t (by simpa using hzero)
  have hm : 2 ≤ p.order := by
    by_contra hnot
    have hlt : p.order < 2 := Nat.lt_of_not_ge hnot
    interval_cases horder : p.order
    · have hp0 : p 0 = 0 := by
        rw [← FormalMultilinearSeries.coeff_eq_zero]
        rw [FormalMultilinearSeries.coeff, hp.coeff_zero]
        exact hz
      exact p.apply_order_ne_zero hpne (horder ▸ hp0)
    · have hp1 : p 1 = 0 := by
        rw [← FormalMultilinearSeries.coeff_eq_zero]
        change p 1 (fun _ ↦ 1) = 0
        rw [← hp.deriv]
        exact hrepeated
      exact p.apply_order_ne_zero hpne (horder ▸ hp1)
  let g : ℂ → ℂ := (Function.swap dslope z)^[p.order] (deBruijnNewmanH t)
  have hgdiff : Differentiable ℂ g := by
    have hiterate : ∀ (n : ℕ) (f : ℂ → ℂ), Differentiable ℂ f →
        Differentiable ℂ ((Function.swap dslope z)^[n] f) := by
      intro n
      induction n with
      | zero => simpa
      | succ n ih =>
          intro f hf
          rw [Function.iterate_succ_apply']
          rw [← differentiableOn_univ]
          exact (differentiableOn_dslope (s := Set.univ) univ_mem).mpr
            (by simpa [differentiableOn_univ] using ih f hf)
    exact hiterate p.order (deBruijnNewmanH t) (differentiable_deBruijnNewmanH t)
  refine ⟨p.order, g, hm, hgdiff, ?_, ?_⟩
  · exact hp.iterate_dslope_fslope_ne_zero hpne
  · intro w
    simpa [g, smul_eq_mul] using hp.eq_pow_order_mul_iterate_dslope w

/-- The complex cosine grows only with the imaginary part of its argument. This horizontal-strip
bound is the domination input for averaging the heat family over real Gaussian translations. -/
theorem norm_complex_cos_le_exp_abs_im (w : ℂ) :
    ‖Complex.cos w‖ ≤ Real.exp |w.im| := by
  have hsum : 2 * ‖Complex.cos w‖ ≤ Real.exp (-w.im) + Real.exp w.im := by
    calc
      2 * ‖Complex.cos w‖ = ‖2 * Complex.cos w‖ := by simp
      _ = ‖Complex.exp (w * I) + Complex.exp (-w * I)‖ := by
        rw [Complex.two_cos]
      _ ≤ ‖Complex.exp (w * I)‖ + ‖Complex.exp (-w * I)‖ := norm_add_le _ _
      _ = Real.exp (-w.im) + Real.exp w.im := by
        simp [Complex.norm_exp]
  have hneg : Real.exp (-w.im) ≤ Real.exp |w.im| :=
    Real.exp_le_exp.mpr (neg_le_abs w.im)
  have hpos : Real.exp w.im ≤ Real.exp |w.im| :=
    Real.exp_le_exp.mpr (le_abs_self w.im)
  linarith

/-- The centered Gaussian of variance two has Fourier transform `exp (-a²)`. -/
theorem integral_cexp_mul_I_gaussianReal_zero_two (a : ℝ) :
    ∫ y : ℝ, Complex.exp (a * y * I) ∂ProbabilityTheory.gaussianReal 0 2 =
      Complex.exp (-(a : ℂ) ^ 2) := by
  rw [← MeasureTheory.charFun_apply_real,
    ProbabilityTheory.charFun_gaussianReal]
  congr 1
  push_cast
  ring

theorem integrable_cexp_mul_I_gaussianReal_zero_two (a : ℝ) :
    MeasureTheory.Integrable (fun y : ℝ ↦ Complex.exp (a * y * I))
      (ProbabilityTheory.gaussianReal 0 2) := by
  have h := BoundedContinuousFunction.integrable (ProbabilityTheory.gaussianReal 0 2)
    (BoundedContinuousFunction.innerProbChar a)
  apply h.congr
  filter_upwards with y
  simp only [BoundedContinuousFunction.innerProbChar_apply]
  congr 1
  rw [Real.inner_apply]
  push_cast
  ring

/-- Real cosine and sine averages under the centered variance-two Gaussian. -/
theorem integral_cos_gaussianReal_zero_two (a : ℝ) :
    ∫ y : ℝ, Real.cos (a * y) ∂ProbabilityTheory.gaussianReal 0 2 =
      Real.exp (-a ^ 2) := by
  have hre :
      (∫ y : ℝ, (Complex.exp (a * y * I)).re
          ∂ProbabilityTheory.gaussianReal 0 2) =
        (∫ y : ℝ, Complex.exp (a * y * I)
          ∂ProbabilityTheory.gaussianReal 0 2).re :=
    integral_re (integrable_cexp_mul_I_gaussianReal_zero_two a)
  rw [integral_cexp_mul_I_gaussianReal_zero_two] at hre
  have hleft (y : ℝ) : (Complex.exp (a * y * I)).re = Real.cos (a * y) := by
    have harg : (a : ℂ) * y * I = ((a * y : ℝ) : ℂ) * I := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_mul_I_re (a * y)
  have hright : (Complex.exp (-(a : ℂ) ^ 2)).re = Real.exp (-a ^ 2) := by
    have harg : -(a : ℂ) ^ 2 = ((-a ^ 2 : ℝ) : ℂ) := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_re (-a ^ 2)
  simpa only [hleft, hright] using hre

theorem integral_sin_gaussianReal_zero_two (a : ℝ) :
    ∫ y : ℝ, Real.sin (a * y) ∂ProbabilityTheory.gaussianReal 0 2 = 0 := by
  have him :
      (∫ y : ℝ, (Complex.exp (a * y * I)).im
          ∂ProbabilityTheory.gaussianReal 0 2) =
        (∫ y : ℝ, Complex.exp (a * y * I)
          ∂ProbabilityTheory.gaussianReal 0 2).im :=
    integral_im (integrable_cexp_mul_I_gaussianReal_zero_two a)
  rw [integral_cexp_mul_I_gaussianReal_zero_two] at him
  have hleft (y : ℝ) : (Complex.exp (a * y * I)).im = Real.sin (a * y) := by
    have harg : (a : ℂ) * y * I = ((a * y : ℝ) : ℂ) * I := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_mul_I_im (a * y)
  have hright : (Complex.exp (-(a : ℂ) ^ 2)).im = 0 := by
    have harg : -(a : ℂ) ^ 2 = ((-a ^ 2 : ℝ) : ℂ) := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_im (-a ^ 2)
  simpa only [hleft, hright] using him

/-- Gaussian averaging of a complex cosine after a real translation. -/
theorem integral_complex_cos_gaussianReal_shift (w : ℂ) (r u : ℝ) :
    ∫ y : ℝ, Complex.cos ((w + (r * y : ℝ)) * (u : ℂ))
        ∂ProbabilityTheory.gaussianReal 0 2 =
      (Real.exp (-(r * u) ^ 2) : ℂ) * Complex.cos (w * (u : ℂ)) := by
  let μ := ProbabilityTheory.gaussianReal 0 2
  let a := r * u
  have hexp := integrable_cexp_mul_I_gaussianReal_zero_two a
  have hcos_point (y : ℝ) :
      (Complex.exp (a * y * I)).re = Real.cos (a * y) := by
    have harg : (a : ℂ) * y * I = ((a * y : ℝ) : ℂ) * I := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_mul_I_re (a * y)
  have hsin_point (y : ℝ) :
      (Complex.exp (a * y * I)).im = Real.sin (a * y) := by
    have harg : (a : ℂ) * y * I = ((a * y : ℝ) : ℂ) * I := by
      push_cast
      rfl
    rw [harg]
    exact Complex.exp_ofReal_mul_I_im (a * y)
  have hcosR : MeasureTheory.Integrable (fun y : ℝ ↦ Real.cos (a * y)) μ :=
    hexp.re.congr (MeasureTheory.ae_of_all μ hcos_point)
  have hsinR : MeasureTheory.Integrable (fun y : ℝ ↦ Real.sin (a * y)) μ :=
    hexp.im.congr (MeasureTheory.ae_of_all μ hsin_point)
  have hcosC : MeasureTheory.Integrable (fun y : ℝ ↦ (Real.cos (a * y) : ℂ)) μ :=
    hcosR.ofReal
  have hsinC : MeasureTheory.Integrable (fun y : ℝ ↦ (Real.sin (a * y) : ℂ)) μ :=
    hsinR.ofReal
  have hpoint (y : ℝ) :
      Complex.cos ((w + (r * y : ℝ)) * (u : ℂ)) =
        Complex.cos (w * (u : ℂ)) * (Real.cos (a * y) : ℂ) -
          Complex.sin (w * (u : ℂ)) * (Real.sin (a * y) : ℂ) := by
    have harg :
        (w + (r * y : ℝ)) * (u : ℂ) =
          w * (u : ℂ) + ((a * y : ℝ) : ℂ) := by
      dsimp [a]
      push_cast
      ring
    rw [harg, Complex.cos_add, ← Complex.ofReal_cos, ← Complex.ofReal_sin]
  rw [MeasureTheory.integral_congr_ae (MeasureTheory.ae_of_all μ hpoint)]
  rw [MeasureTheory.integral_sub (hcosC.const_mul _) (hsinC.const_mul _),
    MeasureTheory.integral_const_mul, MeasureTheory.integral_const_mul]
  have hcosIntegral :
      (∫ y : ℝ, (Real.cos (a * y) : ℂ) ∂μ) =
        (Real.exp (-a ^ 2) : ℂ) := by
    rw [integral_complex_ofReal, integral_cos_gaussianReal_zero_two]
  have hsinIntegral :
      (∫ y : ℝ, (Real.sin (a * y) : ℂ) ∂μ) = 0 := by
    rw [integral_complex_ofReal, integral_sin_gaussianReal_zero_two]
    norm_num
  rw [hcosIntegral, hsinIntegral]
  dsimp [a]
  ring

/-- The defining kernel of `H_t`, with an additional real Gaussian translation in `z`, is
integrable on the product space. The sharper horizontal-strip cosine bound makes the majorant
independent of the Gaussian variable. -/
theorem integrable_deBruijnNewmanH_gaussian_shift_kernel (t r : ℝ) (w : ℂ) :
    MeasureTheory.Integrable
      (fun p : ℝ × ℝ ↦
        (((Real.exp (t * p.2 ^ 2) * deBruijnNewmanPhi p.2 : ℝ) : ℂ) *
          Complex.cos ((w + (r * p.1 : ℝ)) * (p.2 : ℂ))))
      ((ProbabilityTheory.gaussianReal 0 2).prod
        (MeasureTheory.volume.restrict (Ioi 0))) := by
  let μ := ProbabilityTheory.gaussianReal 0 2
  let ν : MeasureTheory.Measure ℝ := MeasureTheory.volume.restrict (Ioi 0)
  let M : ℝ → ℝ := fun u ↦
    (1 + u ^ 2) * Real.exp (|t| * u ^ 2 + |w.im| * u) *
      ‖deBruijnNewmanPhi u‖
  have hmajor : MeasureTheory.Integrable M ν := by
    simpa only [M, ν, MeasureTheory.IntegrableOn] using
      integrableOn_one_add_sq_mul_exp_mul_norm_deBruijnNewmanPhi
        |t| (abs_nonneg t) |w.im|
  have hmajorProd : MeasureTheory.Integrable (fun p : ℝ × ℝ ↦ M p.2) (μ.prod ν) :=
    hmajor.comp_snd μ
  apply MeasureTheory.Integrable.mono' hmajorProd
  · have hscalar : MeasureTheory.AEStronglyMeasurable
        (fun p : ℝ × ℝ ↦ Real.exp (t * p.2 ^ 2) * deBruijnNewmanPhi p.2)
        (μ.prod ν) := by
      have hexp : MeasureTheory.AEStronglyMeasurable
          (fun p : ℝ × ℝ ↦ Real.exp (t * p.2 ^ 2)) (μ.prod ν) :=
        (by fun_prop : Continuous (fun p : ℝ × ℝ ↦ Real.exp (t * p.2 ^ 2))).aestronglyMeasurable
      have hphi :=
        (aestronglyMeasurable_deBruijnNewmanPhi ν).comp_snd (μ := μ)
      exact hexp.mul hphi
    have hcos : MeasureTheory.AEStronglyMeasurable
        (fun p : ℝ × ℝ ↦
          Complex.cos ((w + (r * p.1 : ℝ)) * (p.2 : ℂ))) (μ.prod ν) :=
      (by fun_prop : Continuous (fun p : ℝ × ℝ ↦
        Complex.cos ((w + (r * p.1 : ℝ)) * (p.2 : ℂ)))).aestronglyMeasurable
    exact (Complex.continuous_ofReal.comp_aestronglyMeasurable hscalar).mul hcos
  · have hu : ∀ᵐ p ∂μ.prod ν, p.2 ∈ Ioi (0 : ℝ) :=
      (MeasureTheory.Measure.quasiMeasurePreserving_snd (μ := μ) (ν := ν)).ae
        (MeasureTheory.ae_restrict_mem measurableSet_Ioi)
    filter_upwards [hu] with p hp
    have hu0 : 0 ≤ p.2 := hp.le
    have hcos :
        ‖Complex.cos ((w + (r * p.1 : ℝ)) * (p.2 : ℂ))‖ ≤
          Real.exp (|w.im| * p.2) := by
      refine (norm_complex_cos_le_exp_abs_im _).trans_eq ?_
      congr 1
      simp [abs_mul, abs_of_nonneg hu0]
    rw [norm_mul, norm_real, Real.norm_eq_abs, abs_mul,
      abs_of_pos (Real.exp_pos _), ← Real.norm_eq_abs]
    calc
      Real.exp (t * p.2 ^ 2) * ‖deBruijnNewmanPhi p.2‖ *
          ‖Complex.cos ((w + (r * p.1 : ℝ)) * (p.2 : ℂ))‖ ≤
        Real.exp (|t| * p.2 ^ 2) * ‖deBruijnNewmanPhi p.2‖ *
          Real.exp (|w.im| * p.2) := by
        gcongr
        exact le_abs_self t
      _ ≤ M p.2 := by
        dsimp [M]
        rw [Real.exp_add]
        calc
          Real.exp (|t| * p.2 ^ 2) * ‖deBruijnNewmanPhi p.2‖ *
                Real.exp (|w.im| * p.2) =
              1 * (Real.exp (|t| * p.2 ^ 2) * Real.exp (|w.im| * p.2) *
                ‖deBruijnNewmanPhi p.2‖) := by ring
          _ ≤ (1 + p.2 ^ 2) *
              (Real.exp (|t| * p.2 ^ 2) * Real.exp (|w.im| * p.2) *
                ‖deBruijnNewmanPhi p.2‖) := by
            gcongr
            nlinarith [sq_nonneg p.2]
          _ = _ := by
            rw [Real.norm_eq_abs]
            ring

/-- Averaging `H_t` over a centered real Gaussian translation of size `r` exactly moves the heat
parameter backwards by `r²`. -/
theorem integral_deBruijnNewmanH_gaussian_shift (t r : ℝ) (w : ℂ) :
    ∫ y : ℝ, deBruijnNewmanH t (w + (r * y : ℝ))
        ∂ProbabilityTheory.gaussianReal 0 2 =
      deBruijnNewmanH (t - r ^ 2) w := by
  have hswap :
      (∫ y : ℝ, (∫ u : ℝ in Ioi 0,
          (((Real.exp (t * u ^ 2) * deBruijnNewmanPhi u : ℝ) : ℂ) *
            Complex.cos ((w + (r * y : ℝ)) * (u : ℂ))))
          ∂ProbabilityTheory.gaussianReal 0 2) =
        ∫ u : ℝ in Ioi 0, (∫ y : ℝ,
          (((Real.exp (t * u ^ 2) * deBruijnNewmanPhi u : ℝ) : ℂ) *
            Complex.cos ((w + (r * y : ℝ)) * (u : ℂ)))
          ∂ProbabilityTheory.gaussianReal 0 2) :=
    MeasureTheory.integral_integral_swap
      (integrable_deBruijnNewmanH_gaussian_shift_kernel t r w)
  simp_rw [deBruijnNewmanH]
  rw [hswap]
  apply MeasureTheory.integral_congr_ae
  apply MeasureTheory.ae_of_all
  intro u
  simp only
  rw [MeasureTheory.integral_const_mul,
    integral_complex_cos_gaussianReal_shift]
  have hexp :
      Real.exp (t * u ^ 2) * Real.exp (-(r * u) ^ 2) =
        Real.exp ((t - r ^ 2) * u ^ 2) := by
    rw [← Real.exp_add]
    congr 1
    ring
  calc
    ((Real.exp (t * u ^ 2) * deBruijnNewmanPhi u : ℝ) : ℂ) *
          ((Real.exp (-(r * u) ^ 2) : ℂ) * Complex.cos (w * (u : ℂ))) =
        (((Real.exp (t * u ^ 2) * Real.exp (-(r * u) ^ 2)) *
          deBruijnNewmanPhi u : ℝ) : ℂ) * Complex.cos (w * (u : ℂ)) := by
      push_cast
      ring
    _ = (((Real.exp ((t - r ^ 2) * u ^ 2) * deBruijnNewmanPhi u : ℝ) : ℂ) *
        Complex.cos (w * (u : ℂ))) := by rw [hexp]

/-- Exact square-root-scale representation around a repeated zero. This is the pre-limit identity
whose Gaussian polynomial part becomes the backward Hermite model as `r → 0`. -/
theorem exists_deBruijnNewmanH_repeated_zero_gaussian_scaling
    {t : ℝ} {z : ℂ} (hz : deBruijnNewmanH t z = 0)
    (hrepeated : deriv (deBruijnNewmanH t) z = 0) :
    ∃ (m : ℕ) (g : ℂ → ℂ), 2 ≤ m ∧ Differentiable ℂ g ∧ g z ≠ 0 ∧
      ∀ (r : ℝ) (ξ : ℂ),
        deBruijnNewmanH (t - r ^ 2) (z + (r : ℂ) * ξ) =
          (r : ℂ) ^ m *
            ∫ y : ℝ, (ξ + (y : ℂ)) ^ m *
              g (z + (r : ℂ) * (ξ + (y : ℂ)))
              ∂ProbabilityTheory.gaussianReal 0 2 := by
  obtain ⟨m, g, hm, hgdiff, hgzero, hfactor⟩ :=
    exists_deBruijnNewmanH_repeated_zero_entire_factor hz hrepeated
  refine ⟨m, g, hm, hgdiff, hgzero, ?_⟩
  intro r ξ
  rw [← integral_deBruijnNewmanH_gaussian_shift t r (z + (r : ℂ) * ξ)]
  calc
    (∫ y : ℝ, deBruijnNewmanH t
          (z + (r : ℂ) * ξ + (r * y : ℝ))
          ∂ProbabilityTheory.gaussianReal 0 2) =
        ∫ y : ℝ, (r : ℂ) ^ m *
          ((ξ + (y : ℂ)) ^ m *
            g (z + (r : ℂ) * (ξ + (y : ℂ))))
          ∂ProbabilityTheory.gaussianReal 0 2 := by
      apply MeasureTheory.integral_congr_ae
      apply MeasureTheory.ae_of_all
      intro y
      have harg :
          z + (r : ℂ) * ξ + (r * y : ℝ) =
            z + (r : ℂ) * (ξ + (y : ℂ)) := by
        push_cast
        ring
      simp only
      rw [harg, hfactor]
      simp only [add_sub_cancel_left, mul_pow]
      ring
    _ = (r : ℂ) ^ m *
          ∫ y : ℝ, (ξ + (y : ℂ)) ^ m *
            g (z + (r : ℂ) * (ξ + (y : ℂ)))
            ∂ProbabilityTheory.gaussianReal 0 2 := by
      rw [MeasureTheory.integral_const_mul]

/-- The monomial obtained after one unit of backward heat evolution, in the normalization used by
the local `sqrt (t-s)` blow-up. -/
def deBruijnNewmanBackwardHermite : ℕ → ℝ[X]
  | 0 => 1
  | n + 1 => X * deBruijnNewmanBackwardHermite n +
      C 2 * (deBruijnNewmanBackwardHermite n).derivative

@[simp]
theorem deBruijnNewmanBackwardHermite_zero :
    deBruijnNewmanBackwardHermite 0 = 1 := rfl

theorem deBruijnNewmanBackwardHermite_succ (n : ℕ) :
    deBruijnNewmanBackwardHermite (n + 1) =
      X * deBruijnNewmanBackwardHermite n +
        C 2 * (deBruijnNewmanBackwardHermite n).derivative := rfl

/-- The exponential generating function for the backward Hermite family, expressed directly as
an identity of iterated complex derivatives. -/
theorem iteratedDeriv_cexp_mul_add_sq_eq_deBruijnNewmanBackwardHermite
    (n : ℕ) (xi z : ℂ) :
    iteratedDeriv n (fun s : ℂ => Complex.exp (s * xi + s ^ 2)) z =
      (deBruijnNewmanBackwardHermite n).aeval (xi + 2 * z) *
        Complex.exp (z * xi + z ^ 2) := by
  induction n generalizing z with
  | zero => simp [deBruijnNewmanBackwardHermite]
  | succ n ih =>
      rw [iteratedDeriv_succ, funext (fun w => ih w)]
      have hinner0 :=
        (hasDerivAt_const z xi).add ((hasDerivAt_id z).const_mul (2 : ℂ))
      have hinner := hinner0.congr_of_eventuallyEq
        (show (fun w : ℂ => xi + 2 * w) =ᶠ[nhds z]
            ((fun _ : ℂ => xi) + fun w : ℂ => 2 * id w) from by
          filter_upwards with w
          rfl)
      have hp :=
        ((deBruijnNewmanBackwardHermite n).hasDerivAt_aeval (xi + 2 * z)).comp z hinner
      have hquad0 :=
        ((hasDerivAt_id z).mul_const xi).add ((hasDerivAt_id z).pow 2)
      have hquad1 := hquad0.congr_of_eventuallyEq
        (show (fun w : ℂ => w * xi + w ^ 2) =ᶠ[nhds z]
            ((fun w : ℂ => id w * xi) + id ^ 2) from by
          filter_upwards with w
          rfl)
      have hquad := hquad1.congr_deriv
        (show 1 * xi + (2 : ℂ) * id z ^ (2 - 1) * 1 = xi + 2 * z by
          simp only [id_eq, one_mul, Nat.reduceSubDiff, pow_one, mul_one])
      have hexp := Complex.hasDerivAt_exp (z * xi + z ^ 2) |>.comp z hquad
      have hderiv :
          deriv (fun w : ℂ =>
            (deBruijnNewmanBackwardHermite n).aeval (xi + 2 * w) *
              Complex.exp (w * xi + w ^ 2)) z =
            ((deBruijnNewmanBackwardHermite n).derivative.aeval (xi + 2 * z) * 2) *
                Complex.exp (z * xi + z ^ 2) +
              (deBruijnNewmanBackwardHermite n).aeval (xi + 2 * z) *
                (Complex.exp (z * xi + z ^ 2) * (xi + 2 * z)) := by
        have hfun :
            (((fun x : ℂ => (deBruijnNewmanBackwardHermite n).aeval x) ∘
                fun w : ℂ => xi + 2 * w) *
              Complex.exp ∘ fun w : ℂ => w * xi + w ^ 2) =
              fun w : ℂ => (deBruijnNewmanBackwardHermite n).aeval (xi + 2 * w) *
                Complex.exp (w * xi + w ^ 2) := by
          funext w
          rfl
        rw [← hfun]
        simpa only [Function.comp_apply, Pi.mul_apply, zero_add, mul_one] using
          hp.mul hexp |>.deriv
      rw [hderiv]
      simp only [deBruijnNewmanBackwardHermite_succ, aeval_add, aeval_mul, aeval_X,
        aeval_C]
      norm_num
      ring

theorem integral_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite_zero
    (n : ℕ) :
    ∫ y : ℝ, (y : ℂ) ^ n ∂ProbabilityTheory.gaussianReal 0 2 =
      (deBruijnNewmanBackwardHermite n).aeval 0 := by
  have hmgf := ProbabilityTheory.iteratedDeriv_complexMGF
    (X := id) (μ := ProbabilityTheory.gaussianReal 0 2) (z := 0) (by simp) n
  have hfun :
      ProbabilityTheory.complexMGF id (ProbabilityTheory.gaussianReal 0 2) =
        fun z : ℂ => Complex.exp (z ^ 2) := by
    funext z
    rw [ProbabilityTheory.complexMGF_id_gaussianReal]
    norm_num
  rw [hfun] at hmgf
  have hderiv :=
    iteratedDeriv_cexp_mul_add_sq_eq_deBruijnNewmanBackwardHermite n 0 0
  norm_num at hderiv
  rw [hderiv] at hmgf
  simpa only [id_eq, zero_mul, Complex.exp_zero, mul_one, ofReal_pow] using hmgf.symm

private theorem deBruijnNewmanBackwardHermite_aeval_eq_gaussian_sum
    (n : ℕ) (xi : ℂ) :
    (deBruijnNewmanBackwardHermite n).aeval xi =
      ∑ i ∈ Finset.range (n + 1),
        n.choose i * xi ^ i *
          (deBruijnNewmanBackwardHermite (n - i)).aeval 0 := by
  have hleibniz := iteratedDeriv_mul (n := n) (x := (0 : ℂ))
    (f := fun z : ℂ => Complex.exp (xi * z))
    (g := fun z : ℂ => Complex.exp (z ^ 2)) (by fun_prop) (by fun_prop)
  have hproduct :
      ((fun z : ℂ => Complex.exp (xi * z)) *
          fun z : ℂ => Complex.exp (z ^ 2)) =
        fun z : ℂ => Complex.exp (z * xi + z ^ 2) := by
    funext z
    change Complex.exp (xi * z) * Complex.exp (z ^ 2) =
      Complex.exp (z * xi + z ^ 2)
    rw [← Complex.exp_add]
    congr 1
    ring
  rw [hproduct,
    iteratedDeriv_cexp_mul_add_sq_eq_deBruijnNewmanBackwardHermite n xi 0] at hleibniz
  simp only [iteratedDeriv_cexp_const_mul] at hleibniz
  have hquad (k : ℕ) :
      iteratedDeriv k (fun z : ℂ => Complex.exp (z ^ 2)) 0 =
        (deBruijnNewmanBackwardHermite k).aeval 0 := by
    have h := iteratedDeriv_cexp_mul_add_sq_eq_deBruijnNewmanBackwardHermite k 0 0
    norm_num at h
    exact h
  simp_rw [hquad] at hleibniz
  simpa using hleibniz

theorem integrable_pow_gaussianReal_zero_two (n : ℕ) :
    MeasureTheory.Integrable (fun y : ℝ => (y : ℂ) ^ n)
      (ProbabilityTheory.gaussianReal 0 2) := by
  have h :=
    ProbabilityTheory.integrable_pow_mul_cexp_of_re_mem_interior_integrableExpSet
      (X := id) (μ := ProbabilityTheory.gaussianReal 0 2) (z := 0) (by simp) n
  simpa only [id_eq, zero_mul, Complex.exp_zero, mul_one, ofReal_pow] using h

/-- The shifted moments of the centered variance-two Gaussian are exactly the backward Hermite
polynomials. This identifies the polynomial part of the repeated-zero heat scaling. -/
theorem integral_add_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite
    (n : ℕ) (xi : ℂ) :
    ∫ y : ℝ, (xi + (y : ℂ)) ^ n ∂ProbabilityTheory.gaussianReal 0 2 =
      (deBruijnNewmanBackwardHermite n).aeval xi := by
  let μ := ProbabilityTheory.gaussianReal 0 2
  calc
    (∫ y : ℝ, (xi + (y : ℂ)) ^ n ∂μ) =
        ∫ y : ℝ, ∑ i ∈ Finset.range (n + 1),
          xi ^ i * (y : ℂ) ^ (n - i) * n.choose i ∂μ := by
      apply MeasureTheory.integral_congr_ae
      apply MeasureTheory.ae_of_all
      intro y
      exact add_pow xi (y : ℂ) n
    _ = ∑ i ∈ Finset.range (n + 1),
          ∫ y : ℝ, xi ^ i * (y : ℂ) ^ (n - i) * n.choose i ∂μ := by
      rw [MeasureTheory.integral_finsetSum]
      intro i hi
      exact ((integrable_pow_gaussianReal_zero_two (n - i)).const_mul
        (xi ^ i)).mul_const (n.choose i : ℂ)
    _ = ∑ i ∈ Finset.range (n + 1),
          n.choose i * xi ^ i *
            (deBruijnNewmanBackwardHermite (n - i)).aeval 0 := by
      apply Finset.sum_congr rfl
      intro i hi
      rw [MeasureTheory.integral_mul_const, MeasureTheory.integral_const_mul,
        integral_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite_zero]
      ring
    _ = (deBruijnNewmanBackwardHermite n).aeval xi :=
      (deBruijnNewmanBackwardHermite_aeval_eq_gaussian_sum n xi).symm

/-- The heat family is uniformly bounded on every closed horizontal strip. The bound depends on
the strip and time, but not on the real part. -/
theorem exists_norm_deBruijnNewmanH_le_of_abs_im_le (t B : ℝ) :
    ∃ C : ℝ, ∀ w : ℂ, |w.im| ≤ B → ‖deBruijnNewmanH t w‖ ≤ C := by
  let μ : MeasureTheory.Measure ℝ := MeasureTheory.volume.restrict (Ioi 0)
  let M : ℝ → ℝ := fun u ↦
    (1 + u ^ 2) * Real.exp (|t| * u ^ 2 + B * u) * ‖deBruijnNewmanPhi u‖
  have hM : MeasureTheory.Integrable M μ := by
    simpa only [M, μ, MeasureTheory.IntegrableOn] using
      integrableOn_one_add_sq_mul_exp_mul_norm_deBruijnNewmanPhi |t| (abs_nonneg t) B
  refine ⟨∫ u : ℝ, M u ∂μ, ?_⟩
  intro w hw
  rw [deBruijnNewmanH]
  apply MeasureTheory.norm_integral_le_of_norm_le hM
  rw [MeasureTheory.ae_restrict_iff' measurableSet_Ioi]
  filter_upwards with u hu
  have hu0 : 0 ≤ u := hu.le
  have hcos : ‖Complex.cos (w * (u : ℂ))‖ ≤ Real.exp (B * u) := by
    refine (norm_complex_cos_le_exp_abs_im _).trans ?_
    apply Real.exp_le_exp.mpr
    have him : (w * (u : ℂ)).im = w.im * u := by simp
    rw [him, abs_mul, abs_of_nonneg hu0]
    exact mul_le_mul_of_nonneg_right hw hu0
  rw [norm_mul, norm_real, Real.norm_eq_abs, abs_mul,
    abs_of_pos (Real.exp_pos _), ← Real.norm_eq_abs]
  calc
    Real.exp (t * u ^ 2) * ‖deBruijnNewmanPhi u‖ *
          ‖Complex.cos (w * (u : ℂ))‖ ≤
        Real.exp (|t| * u ^ 2) * ‖deBruijnNewmanPhi u‖ *
          Real.exp (B * u) := by
      gcongr
      exact le_abs_self t
    _ ≤ M u := by
      dsimp [M]
      rw [Real.exp_add]
      calc
        Real.exp (|t| * u ^ 2) * ‖deBruijnNewmanPhi u‖ * Real.exp (B * u) =
            1 * (Real.exp (|t| * u ^ 2) * Real.exp (B * u) *
              ‖deBruijnNewmanPhi u‖) := by ring
        _ ≤ (1 + u ^ 2) *
            (Real.exp (|t| * u ^ 2) * Real.exp (B * u) *
              ‖deBruijnNewmanPhi u‖) := by
          gcongr
          nlinarith [sq_nonneg u]
        _ = _ := by
          rw [Real.norm_eq_abs]
          ring

/-- An entire residual factor in a global zero factorization of `H_t` inherits uniform boundedness
on every horizontal strip. Near the divided-out zero this is compactness; away from it the
factorization and the strip bound for `H_t` apply. -/
theorem exists_norm_deBruijnNewmanH_entire_factor_le_of_abs_im_le
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ}
    (hgdiff : Differentiable ℂ g)
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w)
    (B : ℝ) :
    ∃ C : ℝ, ∀ w : ℂ, |w.im| ≤ B → ‖g w‖ ≤ C := by
  obtain ⟨C0, hC0⟩ := (isCompact_closedBall z 1).exists_bound_of_continuousOn
    hgdiff.continuous.continuousOn
  obtain ⟨C1, hC1⟩ := exists_norm_deBruijnNewmanH_le_of_abs_im_le t B
  refine ⟨max C0 C1, ?_⟩
  intro w hw
  by_cases hnear : ‖w - z‖ ≤ 1
  · exact (hC0 w (by simpa [Metric.mem_closedBall, dist_eq_norm] using hnear)).trans
      (le_max_left _ _)
  · have hpow : 1 ≤ ‖w - z‖ ^ m := one_le_pow₀ (le_of_not_ge hnear)
    calc
      ‖g w‖ = 1 * ‖g w‖ := by ring
      _ ≤ ‖w - z‖ ^ m * ‖g w‖ :=
        mul_le_mul_of_nonneg_right hpow (norm_nonneg _)
      _ = ‖deBruijnNewmanH t w‖ := by rw [hfactor, norm_mul, norm_pow]
      _ ≤ C1 := hC1 w hw
      _ ≤ max C0 C1 := le_max_right _ _

theorem integrable_one_add_abs_pow_gaussianReal_zero_two (m : ℕ) :
    MeasureTheory.Integrable (fun y : ℝ => (1 + |y|) ^ m)
      (ProbabilityTheory.gaussianReal 0 2) := by
  rw [show (fun y : ℝ => (1 + |y|) ^ m) = fun y : ℝ =>
      ∑ i ∈ Finset.range (m + 1), 1 ^ i * |y| ^ (m - i) * m.choose i by
    funext y
    exact add_pow 1 |y| m]
  apply MeasureTheory.integrable_finsetSum
  intro i hi
  have hpow := (integrable_pow_gaussianReal_zero_two (m - i)).norm
  have habs : MeasureTheory.Integrable (fun y : ℝ => |y| ^ (m - i))
      (ProbabilityTheory.gaussianReal 0 2) := by
    simpa only [norm_pow, norm_real, Complex.norm_real, Real.norm_eq_abs] using hpow
  simpa only [one_pow, one_mul] using habs.mul_const (m.choose i : ℝ)

/-- Joint continuity at zero scale of the Gaussian residual-factor integral. The proof uses the
horizontal-strip bound inherited from the source heat family, not unrestricted entire growth. -/
theorem continuousAt_deBruijnNewman_gaussian_scaled_factor_integral
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ}
    (hgdiff : Differentiable ℂ g)
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w)
    (xi : ℂ) :
    ContinuousAt
      (fun p : ℝ × ℂ =>
        ∫ y : ℝ, (p.2 + (y : ℂ)) ^ m *
          g (z + (p.1 : ℂ) * (p.2 + (y : ℂ)))
          ∂ProbabilityTheory.gaussianReal 0 2)
      (0, xi) := by
  let μ := ProbabilityTheory.gaussianReal 0 2
  let A : ℝ := ‖xi‖ + 2
  let B : ℝ := |z.im| + (‖xi‖ + 1)
  obtain ⟨C, hC⟩ := exists_norm_deBruijnNewmanH_entire_factor_le_of_abs_im_le
    (t := t) (z := z) (m := m) (g := g) hgdiff hfactor B
  have hC0 : 0 ≤ C := by
    exact (norm_nonneg (g z)).trans (hC z (by
      dsimp [B]
      linarith [norm_nonneg xi]))
  let bound : ℝ → ℝ := fun y => (A * (1 + |y|)) ^ m * C
  have hbound : MeasureTheory.Integrable bound μ := by
    have h := (integrable_one_add_abs_pow_gaussianReal_zero_two m).const_mul
      (A ^ m * C)
    apply h.congr
    apply MeasureTheory.ae_of_all
    intro y
    dsimp [bound]
    rw [mul_pow]
    ring
  apply MeasureTheory.continuousAt_of_dominated
  · filter_upwards with p
    have hpoly : Continuous (fun y : ℝ => (p.2 + (y : ℂ)) ^ m) := by fun_prop
    have harg : Continuous (fun y : ℝ => z + (p.1 : ℂ) * (p.2 + (y : ℂ))) := by
      fun_prop
    exact (hpoly.mul (hgdiff.continuous.comp harg)).aestronglyMeasurable
  · have hr : ∀ᶠ p : ℝ × ℂ in 𝓝 (0, xi), p.1 ∈ Metric.ball (0 : ℝ) 1 :=
      continuous_fst.continuousAt (Metric.ball_mem_nhds 0 zero_lt_one)
    have hxi : ∀ᶠ p : ℝ × ℂ in 𝓝 (0, xi), p.2 ∈ Metric.ball xi 1 :=
      continuous_snd.continuousAt (Metric.ball_mem_nhds xi zero_lt_one)
    filter_upwards [hr, hxi] with p hpR hpXi
    apply MeasureTheory.ae_of_all
    intro y
    have hrabs : |p.1| ≤ 1 := by
      simpa [Real.dist_eq] using le_of_lt (Metric.mem_ball.mp hpR)
    have hxiSub : ‖p.2 - xi‖ ≤ 1 := by
      simpa [dist_eq_norm] using le_of_lt (Metric.mem_ball.mp hpXi)
    have hxiNorm : ‖p.2‖ ≤ ‖xi‖ + 1 := by
      calc
        ‖p.2‖ = ‖(p.2 - xi) + xi‖ := by ring_nf
        _ ≤ ‖p.2 - xi‖ + ‖xi‖ := norm_add_le _ _
        _ ≤ ‖xi‖ + 1 := by linarith
    have himArg :
        |(z + (p.1 : ℂ) * (p.2 + (y : ℂ))).im| ≤ B := by
      have him :
          (z + (p.1 : ℂ) * (p.2 + (y : ℂ))).im = z.im + p.1 * p.2.im := by
        simp
      rw [him]
      dsimp [B]
      calc
        |z.im + p.1 * p.2.im| ≤ |z.im| + |p.1 * p.2.im| := abs_add_le _ _
        _ ≤ |z.im| + (‖xi‖ + 1) := by
          gcongr
          rw [abs_mul]
          calc
            |p.1| * |p.2.im| ≤ 1 * ‖p.2‖ := by
              gcongr
              exact abs_im_le_norm p.2
            _ ≤ ‖xi‖ + 1 := by simpa using hxiNorm
    have hsum : ‖p.2 + (y : ℂ)‖ ≤ A * (1 + |y|) := by
      calc
        ‖p.2 + (y : ℂ)‖ ≤ ‖p.2‖ + ‖(y : ℂ)‖ := norm_add_le _ _
        _ ≤ (‖xi‖ + 1) + |y| := by
          simpa using add_le_add_right hxiNorm |y|
        _ ≤ A * (1 + |y|) := by
          dsimp [A]
          nlinarith [norm_nonneg xi, abs_nonneg y]
    rw [norm_mul, norm_pow]
    calc
      ‖p.2 + (y : ℂ)‖ ^ m *
          ‖g (z + (p.1 : ℂ) * (p.2 + (y : ℂ)))‖ ≤
        (A * (1 + |y|)) ^ m * C := by
          gcongr
          exact hC _ himArg
      _ = bound y := rfl
  · exact hbound
  · apply MeasureTheory.ae_of_all
    intro y
    have hpoly : ContinuousAt (fun p : ℝ × ℂ => (p.2 + (y : ℂ)) ^ m) (0, xi) := by
      fun_prop
    have harg : ContinuousAt
        (fun p : ℝ × ℂ => z + (p.1 : ℂ) * (p.2 + (y : ℂ))) (0, xi) := by
      fun_prop
    have hgarg : ContinuousAt
        (fun p : ℝ × ℂ => g (z + (p.1 : ℂ) * (p.2 + (y : ℂ)))) (0, xi) :=
      by simpa only [Function.comp_apply] using
        hgdiff.continuous.continuousAt.comp' harg
    exact hpoly.mul hgarg

/-- At every fixed scaled coordinate, the exact repeated-zero Gaussian integral converges to the
backward Hermite model times the nonzero residual factor. -/
theorem tendsto_deBruijnNewman_gaussian_scaled_factor_integral
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ}
    (hgdiff : Differentiable ℂ g)
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w)
    (xi : ℂ) :
    Tendsto
      (fun r : ℝ =>
        ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
          g (z + (r : ℂ) * (xi + (y : ℂ)))
          ∂ProbabilityTheory.gaussianReal 0 2)
      (𝓝 0)
      (𝓝 ((deBruijnNewmanBackwardHermite m).aeval xi * g z)) := by
  have hcont := continuousAt_deBruijnNewman_gaussian_scaled_factor_integral
    hgdiff hfactor xi
  have hpath : Tendsto (fun r : ℝ => (r, xi)) (𝓝 0) (𝓝 (0, xi)) := by
    exact (continuous_id.prodMk continuous_const).tendsto 0
  have h := hcont.tendsto.comp hpath
  change Tendsto
    (fun r : ℝ =>
      ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
        g (z + (r : ℂ) * (xi + (y : ℂ)))
        ∂ProbabilityTheory.gaussianReal 0 2)
    (𝓝 0)
    (𝓝 (∫ y : ℝ, (xi + (y : ℂ)) ^ m *
      g (z + ((0 : ℝ) : ℂ) * (xi + (y : ℂ)))
      ∂ProbabilityTheory.gaussianReal 0 2)) at h
  simpa only [zero_mul, ofReal_zero, add_zero,
    MeasureTheory.integral_mul_const,
    integral_add_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite] using h

/-- The scaled residual-factor integrals converge uniformly to the backward Hermite model on every
compact set of scaled coordinates. -/
theorem tendstoUniformlyOn_deBruijnNewman_gaussian_scaled_factor_integral
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ} {K : Set ℂ}
    (hgdiff : Differentiable ℂ g)
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w)
    (hK : IsCompact K) :
    TendstoUniformlyOn
      (fun r : ℝ => fun xi : ℂ =>
        ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
          g (z + (r : ℂ) * (xi + (y : ℂ)))
          ∂ProbabilityTheory.gaussianReal 0 2)
      (fun xi : ℂ => (deBruijnNewmanBackwardHermite m).aeval xi * g z)
      (𝓝 0) K := by
  rw [Metric.tendstoUniformlyOn_iff]
  intro ε hε
  let F : ℝ × ℂ → ℂ := fun p =>
    ∫ y : ℝ, (p.2 + (y : ℂ)) ^ m *
      g (z + (p.1 : ℂ) * (p.2 + (y : ℂ)))
      ∂ProbabilityTheory.gaussianReal 0 2
  let S : Set (ℝ × ℂ) := ({0} : Set ℝ) ×ˢ K
  have hS : IsCompact S := isCompact_singleton.prod hK
  have hcont : ∀ p ∈ S, ContinuousAt F p := by
    rintro ⟨r, xi⟩ ⟨hr, hxi⟩
    have hr0 : r = 0 := by simpa using hr
    subst r
    exact continuousAt_deBruijnNewman_gaussian_scaled_factor_integral
      hgdiff hfactor xi
  let u : Set (ℂ × ℂ) := {q | dist q.1 q.2 < ε}
  have hu : u ∈ 𝓤 ℂ := Metric.dist_mem_uniformity hε
  have huniform := hS.uniformContinuousAt_of_continuousAt F hcont hu
  rcases Metric.mem_uniformity_dist.1 huniform with ⟨δ, hδ, hδsub⟩
  filter_upwards [Metric.ball_mem_nhds (0 : ℝ) hδ] with r hr
  intro xi hxi
  have hpair : dist ((0 : ℝ), xi) (r, xi) < δ := by
    simpa only [dist_prod_same_right, dist_comm] using (Metric.mem_ball.mp hr)
  have himage := hδsub hpair (show ((0 : ℝ), xi) ∈ S from ⟨by simp, hxi⟩)
  change dist
    ((deBruijnNewmanBackwardHermite m).aeval xi * g z)
    (F (r, xi)) < ε
  have hzero :
      F (0, xi) = (deBruijnNewmanBackwardHermite m).aeval xi * g z := by
    dsimp only [F]
    simp only [Complex.ofReal_zero, zero_mul, add_zero, MeasureTheory.integral_mul_const,
      integral_add_pow_gaussianReal_zero_two_eq_deBruijnNewmanBackwardHermite]
  rw [← hzero]
  exact himage

theorem deBruijnNewmanBackwardHermite_coeff_nonneg :
    ∀ n k : ℕ, 0 ≤ (deBruijnNewmanBackwardHermite n).coeff k := by
  intro n
  induction n with
  | zero =>
      intro k
      rw [deBruijnNewmanBackwardHermite, coeff_one]
      positivity
  | succ n ih =>
      intro k
      cases k with
      | zero =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add]
          simp only [coeff_C_mul, coeff_derivative]
          have hx : (X * deBruijnNewmanBackwardHermite n).coeff 0 = 0 := by simp
          rw [hx, zero_add]
          have h := ih 1
          positivity
      | succ k =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
            coeff_C_mul, coeff_derivative]
          have h1 := ih k
          have h2 := ih (k + 2)
          positivity

theorem deBruijnNewmanBackwardHermite_coeff_succ_zero (n : ℕ) :
    (deBruijnNewmanBackwardHermite (n + 1)).coeff 0 =
      2 * (deBruijnNewmanBackwardHermite n).coeff 1 := by
  rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_C_mul, coeff_derivative]
  simp

theorem deBruijnNewmanBackwardHermite_coeff_succ_succ (n k : ℕ) :
    (deBruijnNewmanBackwardHermite (n + 1)).coeff (k + 1) =
      (deBruijnNewmanBackwardHermite n).coeff k +
        2 * (k + 2) * (deBruijnNewmanBackwardHermite n).coeff (k + 2) := by
  rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
    coeff_C_mul, coeff_derivative]
  norm_num [Nat.cast_add]
  ring

theorem deBruijnNewmanBackwardHermite_coeff_of_lt :
    ∀ {n k : ℕ}, n < k → (deBruijnNewmanBackwardHermite n).coeff k = 0 := by
  intro n
  induction n with
  | zero =>
      intro k hk
      rw [deBruijnNewmanBackwardHermite, coeff_one]
      simp [Nat.ne_of_gt hk]
  | succ n ih =>
      intro k hk
      cases k with
      | zero => omega
      | succ k =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
            coeff_C_mul, coeff_derivative]
          rw [ih (by omega), ih (by omega)]
          ring

theorem deBruijnNewmanBackwardHermite_coeff_self :
    ∀ n : ℕ, (deBruijnNewmanBackwardHermite n).coeff n = 1 := by
  intro n
  induction n with
  | zero => simp [deBruijnNewmanBackwardHermite]
  | succ n ih =>
      rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
        coeff_C_mul, coeff_derivative, ih,
        deBruijnNewmanBackwardHermite_coeff_of_lt (show n < n + 2 by omega)]
      ring

theorem deBruijnNewmanBackwardHermite_coeff_of_odd_add {n k : ℕ}
    (hnk : Odd (n + k)) :
    (deBruijnNewmanBackwardHermite n).coeff k = 0 := by
  induction n generalizing k with
  | zero =>
      rw [zero_add] at hnk
      exact deBruijnNewmanBackwardHermite_coeff_of_lt hnk.pos
  | succ n ih =>
      cases k with
      | zero =>
          rw [deBruijnNewmanBackwardHermite_coeff_succ_zero, ih, mul_zero]
          rwa [Nat.succ_add_eq_add_succ] at hnk
      | succ k =>
          have hfar : Odd (n + (k + 2)) := by
            simpa only [Nat.succ_add_eq_add_succ, Nat.add_assoc] using hnk
          have hnear : Odd (n + k) := by
            have h' : Odd ((n + k) + 2) := by
              simpa only [Nat.add_assoc] using hfar
            exact (Nat.odd_add.mp h').mpr even_two
          rw [deBruijnNewmanBackwardHermite_coeff_succ_succ,
            ih hnear, ih hfar, mul_zero, add_zero]

theorem deBruijnNewmanBackwardHermite_even_const_odd_linear_pos (k : ℕ) :
    0 < (deBruijnNewmanBackwardHermite (2 * k)).coeff 0 ∧
      0 < (deBruijnNewmanBackwardHermite (2 * k + 1)).coeff 1 := by
  induction k with
  | zero => norm_num [deBruijnNewmanBackwardHermite]
  | succ k ih =>
      have hconst :
          0 < (deBruijnNewmanBackwardHermite (2 * k + 2)).coeff 0 := by
        rw [(by omega : 2 * k + 2 = (2 * k + 1) + 1),
          deBruijnNewmanBackwardHermite_coeff_succ_zero]
        have hlin := ih.2
        positivity
      constructor
      · simpa only [Nat.mul_succ] using hconst
      · rw [(by omega : 2 * (k + 1) + 1 = (2 * k + 2) + 1),
          deBruijnNewmanBackwardHermite_coeff_succ_succ]
        have hnonneg := deBruijnNewmanBackwardHermite_coeff_nonneg (2 * k + 2) 2
        positivity

theorem deBruijnNewmanBackwardHermite_natDegree (n : ℕ) :
    (deBruijnNewmanBackwardHermite n).natDegree = n := by
  apply natDegree_eq_of_le_of_coeff_ne_zero
  · rw [natDegree_le_iff_coeff_eq_zero]
    intro k hk
    exact deBruijnNewmanBackwardHermite_coeff_of_lt hk
  · rw [deBruijnNewmanBackwardHermite_coeff_self]
    norm_num

theorem deBruijnNewmanBackwardHermite_monic (n : ℕ) :
    (deBruijnNewmanBackwardHermite n).Monic := by
  rw [Monic, leadingCoeff, deBruijnNewmanBackwardHermite_natDegree,
    deBruijnNewmanBackwardHermite_coeff_self]

theorem deBruijnNewmanBackwardHermite_comp_neg_X :
    ∀ n : ℕ, (deBruijnNewmanBackwardHermite n).comp (-X) =
      C ((-1 : ℝ) ^ n) * deBruijnNewmanBackwardHermite n := by
  intro n
  induction n with
  | zero => simp [deBruijnNewmanBackwardHermite]
  | succ n ih =>
      have hderiv :
          -(deBruijnNewmanBackwardHermite n).derivative.comp (-X) =
            C ((-1 : ℝ) ^ n) * (deBruijnNewmanBackwardHermite n).derivative := by
        simpa only [derivative_comp, derivative_neg, derivative_X, neg_one_mul,
          derivative_mul, derivative_C, zero_mul, zero_add] using
          congrArg derivative ih
      have hderiv' :
          (deBruijnNewmanBackwardHermite n).derivative.comp (-X) =
            -(C ((-1 : ℝ) ^ n) *
              (deBruijnNewmanBackwardHermite n).derivative) :=
        neg_eq_iff_eq_neg.mp hderiv
      rw [deBruijnNewmanBackwardHermite_succ, add_comp, mul_comp, X_comp,
        ih, mul_comp, C_comp, hderiv', pow_succ]
      rw [C_mul]
      norm_num
      ring

theorem deBruijnNewmanBackwardHermite_eval_pos (n : ℕ) {x : ℝ} (hx : 0 < x) :
    0 < (deBruijnNewmanBackwardHermite n).eval x := by
  rw [eval_eq_sum_range, deBruijnNewmanBackwardHermite_natDegree]
  refine Finset.sum_pos'
    (fun k _ ↦ mul_nonneg (deBruijnNewmanBackwardHermite_coeff_nonneg n k)
      (pow_nonneg hx.le k)) ⟨n, by simp, ?_⟩
  rw [deBruijnNewmanBackwardHermite_coeff_self, one_mul]
  positivity

theorem deBruijnNewmanBackwardHermite_eval_ne_zero_of_ne_zero (n : ℕ) {x : ℝ}
    (hx : x ≠ 0) :
    (deBruijnNewmanBackwardHermite n).eval x ≠ 0 := by
  rcases lt_or_gt_of_ne hx with hxneg | hxpos
  · have hpositive := deBruijnNewmanBackwardHermite_eval_pos n (neg_pos.mpr hxneg)
    have hparity :
        (deBruijnNewmanBackwardHermite n).eval (-x) =
          (-1 : ℝ) ^ n * (deBruijnNewmanBackwardHermite n).eval x := by
      simpa [eval_comp] using congrArg (Polynomial.eval x)
        (deBruijnNewmanBackwardHermite_comp_neg_X n)
    intro hzero
    rw [hzero, mul_zero] at hparity
    linarith
  · exact ne_of_gt (deBruijnNewmanBackwardHermite_eval_pos n hxpos)

theorem deBruijnNewmanBackwardHermite_im_ne_zero_of_aeval_eq_zero
    {n : ℕ} {z : ℂ} (hz : (deBruijnNewmanBackwardHermite n).aeval z = 0)
    (hz0 : z ≠ 0) :
    z.im ≠ 0 := by
  intro him
  have hzreal : z = (z.re : ℂ) := by
    apply Complex.ext
    · simp
    · simpa using him
  have hzre : z.re ≠ 0 := by
    intro hre
    apply hz0
    rw [hzreal, hre]
    norm_num
  have heval : (deBruijnNewmanBackwardHermite n).eval z.re = 0 := by
    rw [hzreal, aeval_def] at hz
    change (deBruijnNewmanBackwardHermite n).eval₂ (algebraMap ℝ ℂ)
      ((algebraMap ℝ ℂ) z.re) = 0 at hz
    rw [eval₂_hom] at hz
    exact Complex.ofReal_eq_zero.mp hz
  exact deBruijnNewmanBackwardHermite_eval_ne_zero_of_ne_zero n hzre heval

private theorem exists_nonzero_deBruijnNewmanBackwardHermite_aeval_eq_zero
    (n : ℕ) (hn : 2 ≤ n) :
    ∃ z : ℂ, z ≠ 0 ∧ (deBruijnNewmanBackwardHermite n).aeval z = 0 := by
  rcases Nat.even_or_odd' n with ⟨k, rfl | rfl⟩
  · have hdegree : 0 < (deBruijnNewmanBackwardHermite (2 * k)).degree := by
      rw [← natDegree_pos_iff_degree_pos,
        deBruijnNewmanBackwardHermite_natDegree]
      omega
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_aeval_eq_zero ℂ
      (deBruijnNewmanBackwardHermite (2 * k)) hdegree.ne'
    refine ⟨z, ?_, hz⟩
    intro hz0
    subst z
    rw [aeval_def, eval₂_at_zero] at hz
    have hcoeffzero :
        (deBruijnNewmanBackwardHermite (2 * k)).coeff 0 = 0 := by
      apply FaithfulSMul.algebraMap_injective ℝ ℂ
      simpa using hz
    have hcoeffpos :=
      (deBruijnNewmanBackwardHermite_even_const_odd_linear_pos k).1
    linarith
  · let p := deBruijnNewmanBackwardHermite (2 * k + 1)
    let q := p.divX
    have hcoeffzero : p.coeff 0 = 0 := by
      apply deBruijnNewmanBackwardHermite_coeff_of_odd_add
      simp
    have hqcoeffpos : 0 < q.coeff 0 := by
      simpa [q, p, coeff_divX] using
        (deBruijnNewmanBackwardHermite_even_const_odd_linear_pos k).2
    have hqdegree : 0 < q.degree := by
      rw [← natDegree_pos_iff_degree_pos]
      simp only [q, natDegree_divX_eq_natDegree_tsub_one, p,
        deBruijnNewmanBackwardHermite_natDegree]
      omega
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_aeval_eq_zero ℂ q hqdegree.ne'
    have hz0 : z ≠ 0 := by
      intro hz0
      subst z
      rw [aeval_def, eval₂_at_zero] at hz
      have hcoeffzero' : q.coeff 0 = 0 := by
        apply FaithfulSMul.algebraMap_injective ℝ ℂ
        simpa using hz
      linarith
    refine ⟨z, hz0, ?_⟩
    have hfactor : X * q = p := by
      simpa [q, hcoeffzero] using X_mul_divX_add p
    change p.aeval z = 0
    rw [← hfactor]
    simp [hz]

theorem exists_deBruijnNewmanBackwardHermite_aeval_eq_zero_im_pos
    (n : ℕ) (hn : 2 ≤ n) :
    ∃ z : ℂ, 0 < z.im ∧ (deBruijnNewmanBackwardHermite n).aeval z = 0 := by
  obtain ⟨z, hz0, hz⟩ :=
    exists_nonzero_deBruijnNewmanBackwardHermite_aeval_eq_zero n hn
  have him := deBruijnNewmanBackwardHermite_im_ne_zero_of_aeval_eq_zero hz hz0
  by_cases hupper : 0 < z.im
  · exact ⟨z, hupper, hz⟩
  · have hlower : z.im < 0 := lt_of_le_of_ne (le_of_not_gt hupper) him
    refine ⟨-z, by simpa using neg_pos.mpr hlower, ?_⟩
    have hidentity := congrArg (fun p : ℝ[X] ↦ p.aeval z)
      (deBruijnNewmanBackwardHermite_comp_neg_X n)
    simpa [aeval_comp, hz] using hidentity

/-- An analytic function whose norm at the center is below a positive threshold while its norm on
the boundary is above that threshold has a zero in the closed ball. -/
theorem exists_zero_mem_closedBall_of_analyticOnNhd_of_norm_lt_boundary
    {f : ℂ → ℂ} {z0 : ℂ} {R ε : ℝ}
    (hR : 0 < R) (hε : 0 < ε)
    (hanalytic : AnalyticOnNhd ℂ f (Metric.closedBall z0 R))
    (hcenter : ‖f z0‖ < ε)
    (hboundary : ∀ z ∈ Metric.sphere z0 R, ε < ‖f z‖) :
    ∃ z ∈ Metric.closedBall z0 R, f z = 0 := by
  by_contra hexists
  have hzeroFree : ∀ z ∈ Metric.closedBall z0 R, f z ≠ 0 := by
    intro z hz hzero
    exact hexists ⟨z, hz, hzero⟩
  have hanalyticAbs : AnalyticOnNhd ℂ f (Metric.closedBall z0 |R|) := by
    simpa [abs_of_pos hR] using hanalytic
  have hcircle : CircleIntegrable (fun z : ℂ => Real.log ‖f z‖) z0 R :=
    (hanalyticAbs.mono Metric.sphere_subset_closedBall).meromorphicOn
      |>.circleIntegrable_log_norm
  have hlogBoundary : ∀ z ∈ Metric.sphere z0 |R|,
      Real.log ε ≤ Real.log ‖f z‖ := by
    intro z hz
    have hz' : z ∈ Metric.sphere z0 R := by simpa [abs_of_pos hR] using hz
    have hnorm := hboundary z hz'
    have hnormPos : 0 < ‖f z‖ := hε.trans hnorm
    exact Real.strictMonoOn_log.monotoneOn hε hnormPos hnorm.le
  have havgLower : Real.log ε ≤
      circleAverage (fun z : ℂ => Real.log ‖f z‖) z0 R := by
    calc
      Real.log ε = circleAverage (fun _ : ℂ => Real.log ε) z0 R :=
        (circleAverage_const _ _ _).symm
      _ ≤ circleAverage (fun z : ℂ => Real.log ‖f z‖) z0 R :=
        circleAverage_mono (circleIntegrable_const _ _ _) hcircle hlogBoundary
  have hcenterNe : f z0 ≠ 0 :=
    hzeroFree z0 (Metric.mem_closedBall_self hR.le)
  have hcenterLog : Real.log ‖f z0‖ < Real.log ε :=
    Real.log_lt_log (norm_pos_iff.mpr hcenterNe) hcenter
  have hzeroFreeAbs : ∀ z ∈ Metric.closedBall z0 |R|, f z ≠ 0 := by
    simpa [abs_of_pos hR] using hzeroFree
  rw [hanalyticAbs.circleAverage_log_norm_of_ne_zero hzeroFreeAbs] at havgLower
  exact (not_lt_of_ge havgLower) hcenterLog

/-- A nontrivial entire function has an isolating closed ball at each point, contained in any
prescribed neighborhood of that point. -/
theorem exists_isolating_closedBall_subset_of_analyticOnNhd
    {f : ℂ → ℂ} {z0 : ℂ} {U : Set ℂ}
    (hanalytic : AnalyticOnNhd ℂ f (Set.univ : Set ℂ))
    (hnotLocalZero : ¬f =ᶠ[𝓝 z0] 0)
    (hU : U ∈ 𝓝 z0) :
    ∃ R > 0, (∀ z ∈ Metric.sphere z0 R, f z ≠ 0) ∧
      Metric.closedBall z0 R ⊆ U := by
  have hisolated : ∀ᶠ z in 𝓝[≠] z0, f z ≠ 0 :=
    ((hanalytic z0 (mem_univ z0)).eventually_eq_zero_or_eventually_ne_zero).resolve_left
      hnotLocalZero
  have hnearNonzero : ∀ᶠ z in 𝓝 z0, z ≠ z0 → f z ≠ 0 :=
    eventually_nhdsWithin_iff.mp hisolated
  have hcombined : ∀ᶠ z in 𝓝 z0, (z ≠ z0 → f z ≠ 0) ∧ z ∈ U :=
    hnearNonzero.and hU
  obtain ⟨R, hR, hsubset⟩ := Metric.nhds_basis_closedBall.mem_iff.mp hcombined
  refine ⟨R, hR, ?_, fun z hz => (hsubset hz).2⟩
  intro z hz
  exact (hsubset (Metric.sphere_subset_closedBall hz)).1
    (Metric.ne_of_mem_sphere hz hR.ne')

/-- A positive-imaginary root of the backward Hermite polynomial admits an isolating closed ball
whose imaginary parts have a uniform positive lower bound. -/
theorem exists_deBruijnNewmanBackwardHermite_isolating_upper_closedBall
    (n : ℕ) (hn : 2 ≤ n) :
    ∃ rho : ℂ, ∃ R : ℝ,
      0 < rho.im ∧ 0 < R ∧
      (deBruijnNewmanBackwardHermite n).aeval rho = 0 ∧
      (∀ xi ∈ Metric.sphere rho R,
        (deBruijnNewmanBackwardHermite n).aeval xi ≠ 0) ∧
      (∀ xi ∈ Metric.closedBall rho R, rho.im / 2 < xi.im) := by
  obtain ⟨rho, hrhoIm, hrhoZero⟩ :=
    exists_deBruijnNewmanBackwardHermite_aeval_eq_zero_im_pos n hn
  let p : ℝ[X] := deBruijnNewmanBackwardHermite n
  let f : ℂ → ℂ := fun xi => p.aeval xi
  have hanalytic : AnalyticOnNhd ℂ f (Set.univ : Set ℂ) := by
    intro xi hxi
    exact p.differentiable_aeval.analyticAt xi
  have hnotLocalZero : ¬f =ᶠ[𝓝 rho] 0 := by
    intro hlocal
    have hglobal := hanalytic.eqOn_zero_of_preconnected_of_eventuallyEq_zero
      isPreconnected_univ (mem_univ rho) hlocal
    have hmapZero : p.map (algebraMap ℝ ℂ) = 0 := by
      apply Polynomial.funext
      intro xi
      rw [Polynomial.eval_zero]
      simpa only [f, Polynomial.aeval_def, Polynomial.eval_map, Pi.zero_apply] using
        hglobal (mem_univ xi)
    have hpNe : p ≠ 0 := deBruijnNewmanBackwardHermite_monic n |>.ne_zero
    exact (Polynomial.map_ne_zero_iff
      (FaithfulSMul.algebraMap_injective ℝ ℂ)).2 hpNe hmapZero
  let U : Set ℂ := {xi | rho.im / 2 < xi.im}
  have hUOpen : IsOpen U := isOpen_lt continuous_const Complex.continuous_im
  have hU : U ∈ 𝓝 rho := hUOpen.mem_nhds (by dsimp [U]; linarith)
  obtain ⟨R, hR, hboundary, hball⟩ :=
    exists_isolating_closedBall_subset_of_analyticOnNhd
      hanalytic hnotLocalZero hU
  refine ⟨rho, R, hrhoIm, hR, hrhoZero, ?_, ?_⟩
  · simpa only [f, p] using hboundary
  · intro xi hxi
    exact hball hxi

/-- Exact square-root-scale representation supplied by any entire factorization at the source
time. -/
theorem deBruijnNewmanH_gaussian_scaling_of_factor
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ}
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w)
    (r : ℝ) (xi : ℂ) :
    deBruijnNewmanH (t - r ^ 2) (z + (r : ℂ) * xi) =
      (r : ℂ) ^ m *
        ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
          g (z + (r : ℂ) * (xi + (y : ℂ)))
          ∂ProbabilityTheory.gaussianReal 0 2 := by
  rw [← integral_deBruijnNewmanH_gaussian_shift t r (z + (r : ℂ) * xi)]
  calc
    (∫ y : ℝ, deBruijnNewmanH t
          (z + (r : ℂ) * xi + (r * y : ℝ))
          ∂ProbabilityTheory.gaussianReal 0 2) =
        ∫ y : ℝ, (r : ℂ) ^ m *
          ((xi + (y : ℂ)) ^ m *
            g (z + (r : ℂ) * (xi + (y : ℂ))))
          ∂ProbabilityTheory.gaussianReal 0 2 := by
      apply MeasureTheory.integral_congr_ae
      apply MeasureTheory.ae_of_all
      intro y
      have harg :
          z + (r : ℂ) * xi + (r * y : ℝ) =
            z + (r : ℂ) * (xi + (y : ℂ)) := by
        push_cast
        ring
      simp only
      rw [harg, hfactor]
      simp only [add_sub_cancel_left, mul_pow]
      ring
    _ = (r : ℂ) ^ m *
          ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
            g (z + (r : ℂ) * (xi + (y : ℂ)))
            ∂ProbabilityTheory.gaussianReal 0 2 := by
      rw [MeasureTheory.integral_const_mul]

/-- For every sufficiently small nonzero scale, the residual-factor integral has a zero in one
fixed upper-half-plane disk around a backward Hermite root. -/
theorem eventually_exists_gaussian_scaled_factor_integral_zero_upper
    {t : ℝ} {z : ℂ} {m : ℕ} {g : ℂ → ℂ}
    (hm : 2 ≤ m) (hgdiff : Differentiable ℂ g) (hgzero : g z ≠ 0)
    (hfactor : ∀ w, deBruijnNewmanH t w = (w - z) ^ m * g w) :
    ∃ rho : ℂ, ∃ R : ℝ,
      0 < rho.im ∧ 0 < R ∧
      ∀ᶠ r : ℝ in 𝓝 0, r ≠ 0 →
        ∃ xi ∈ Metric.closedBall rho R,
          (∫ y : ℝ, (xi + (y : ℂ)) ^ m *
            g (z + (r : ℂ) * (xi + (y : ℂ)))
            ∂ProbabilityTheory.gaussianReal 0 2) = 0 ∧
          rho.im / 2 < xi.im := by
  obtain ⟨rho, R, hrhoIm, hR, hrhoZero, hpolyBoundary, hupperBall⟩ :=
    exists_deBruijnNewmanBackwardHermite_isolating_upper_closedBall m hm
  let model : ℂ → ℂ := fun xi =>
    (deBruijnNewmanBackwardHermite m).aeval xi * g z
  have hmodelBoundary : ∀ xi ∈ Metric.sphere rho R, model xi ≠ 0 := by
    intro xi hxi
    exact mul_ne_zero (hpolyBoundary xi hxi) hgzero
  have hsphereNonempty : (Metric.sphere rho R).Nonempty :=
    NormedSpace.sphere_nonempty.mpr hR.le
  have hnormContinuous : ContinuousOn (fun xi : ℂ => ‖model xi‖)
      (Metric.sphere rho R) := by
    fun_prop
  obtain ⟨x, hx, hxmin⟩ :=
    (isCompact_sphere rho R).exists_isMinOn hsphereNonempty hnormContinuous
  let M : ℝ := ‖model x‖
  have hM : 0 < M := norm_pos_iff.mpr (hmodelBoundary x hx)
  have huniform :=
    tendstoUniformlyOn_deBruijnNewman_gaussian_scaled_factor_integral
      hgdiff hfactor (isCompact_closedBall rho R)
  rw [Metric.tendstoUniformlyOn_iff] at huniform
  have hclose := huniform (M / 2) (half_pos hM)
  refine ⟨rho, R, hrhoIm, hR, ?_⟩
  filter_upwards [hclose] with r hr
  intro hr0
  let F : ℂ → ℂ := fun xi =>
    ∫ y : ℝ, (xi + (y : ℂ)) ^ m *
      g (z + (r : ℂ) * (xi + (y : ℂ)))
      ∂ProbabilityTheory.gaussianReal 0 2
  have hcenter : ‖F rho‖ < M / 2 := by
    have h := hr rho (Metric.mem_closedBall_self hR.le)
    simpa only [model, hrhoZero, zero_mul, dist_zero_left] using h
  have hboundary : ∀ xi ∈ Metric.sphere rho R, M / 2 < ‖F xi‖ := by
    intro xi hxi
    have hmin : M ≤ ‖model xi‖ := hxmin hxi
    have htriangle : ‖model xi‖ ≤ dist (model xi) (F xi) + ‖F xi‖ := by
      rw [dist_eq_norm]
      calc
        ‖model xi‖ = ‖(model xi - F xi) + F xi‖ := by congr 1; ring
        _ ≤ ‖model xi - F xi‖ + ‖F xi‖ := norm_add_le _ _
    have hcloseBoundary := hr xi (Metric.sphere_subset_closedBall hxi)
    nlinarith
  have hrComplex : (r : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hr0
  have hrPow : (r : ℂ) ^ m ≠ 0 := pow_ne_zero _ hrComplex
  have hFEq : F = fun xi => ((r : ℂ) ^ m)⁻¹ *
      deBruijnNewmanH (t - r ^ 2) (z + (r : ℂ) * xi) := by
    funext xi
    have hscale := deBruijnNewmanH_gaussian_scaling_of_factor hfactor r xi
    change deBruijnNewmanH (t - r ^ 2) (z + (r : ℂ) * xi) =
      (r : ℂ) ^ m * F xi at hscale
    calc
      F xi = 1 * F xi := by rw [one_mul]
      _ = ((r : ℂ) ^ m)⁻¹ * ((r : ℂ) ^ m) * F xi := by
        rw [inv_mul_cancel₀ hrPow]
      _ = ((r : ℂ) ^ m)⁻¹ * deBruijnNewmanH (t - r ^ 2)
          (z + (r : ℂ) * xi) := by rw [hscale]; ring
  have hFdiff : Differentiable ℂ F := by
    rw [hFEq]
    have hHdiff : Differentiable ℂ (fun xi =>
        deBruijnNewmanH (t - r ^ 2) (z + (r : ℂ) * xi)) :=
      (differentiable_deBruijnNewmanH (t - r ^ 2)).comp (by fun_prop)
    exact (differentiable_const (c := ((r : ℂ) ^ m)⁻¹)).mul hHdiff
  have hFanalytic : AnalyticOnNhd ℂ F (Metric.closedBall rho R) :=
    fun xi hxi => hFdiff.analyticAt xi
  obtain ⟨xi, hxi, hxiZero⟩ :=
    exists_zero_mem_closedBall_of_analyticOnNhd_of_norm_lt_boundary
      hR (half_pos hM) hFanalytic hcenter hboundary
  exact ⟨xi, hxi, hxiZero, hupperBall xi hxi⟩

end

end LeanLab.Riemann
