import LeanLab.Riemann.DeBruijnNewmanDynamics
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic

set_option linter.style.header false

/-!
# Backward Hermite splitting for the de Bruijn-Newman heat family

This file develops the local polynomial and scaled-zero infrastructure for a multiple zero under
backward heat flow. The normalization follows `partial_t H = -partial_z^2 H`: the leading scaled
polynomial is generated by `P_(n+1) = X * P_n + 2 * P_n'`.
-/

open Complex Filter Real Set Topology

namespace LeanLab.Riemann

noncomputable section

open Polynomial

/-- The monomial obtained after one unit of backward heat evolution, in the normalization used by
the local `sqrt (t-s)` blow-up. -/
def deBruijnNewmanBackwardHermite : ℕ → ℝ[X]
  | 0 => 1
  | n + 1 => X * deBruijnNewmanBackwardHermite n +
      C 2 * (deBruijnNewmanBackwardHermite n).derivative

@[simp]
theorem deBruijnNewmanBackwardHermite_zero :
    deBruijnNewmanBackwardHermite 0 = 1 := rfl

theorem deBruijnNewmanBackwardHermite_succ (n : ℕ) :
    deBruijnNewmanBackwardHermite (n + 1) =
      X * deBruijnNewmanBackwardHermite n +
        C 2 * (deBruijnNewmanBackwardHermite n).derivative := rfl

theorem deBruijnNewmanBackwardHermite_coeff_nonneg :
    ∀ n k : ℕ, 0 ≤ (deBruijnNewmanBackwardHermite n).coeff k := by
  intro n
  induction n with
  | zero =>
      intro k
      rw [deBruijnNewmanBackwardHermite, coeff_one]
      positivity
  | succ n ih =>
      intro k
      cases k with
      | zero =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add]
          simp only [coeff_C_mul, coeff_derivative]
          have hx : (X * deBruijnNewmanBackwardHermite n).coeff 0 = 0 := by simp
          rw [hx, zero_add]
          have h := ih 1
          positivity
      | succ k =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
            coeff_C_mul, coeff_derivative]
          have h1 := ih k
          have h2 := ih (k + 2)
          positivity

theorem deBruijnNewmanBackwardHermite_coeff_succ_zero (n : ℕ) :
    (deBruijnNewmanBackwardHermite (n + 1)).coeff 0 =
      2 * (deBruijnNewmanBackwardHermite n).coeff 1 := by
  rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_C_mul, coeff_derivative]
  simp

theorem deBruijnNewmanBackwardHermite_coeff_succ_succ (n k : ℕ) :
    (deBruijnNewmanBackwardHermite (n + 1)).coeff (k + 1) =
      (deBruijnNewmanBackwardHermite n).coeff k +
        2 * (k + 2) * (deBruijnNewmanBackwardHermite n).coeff (k + 2) := by
  rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
    coeff_C_mul, coeff_derivative]
  norm_num [Nat.cast_add]
  ring

theorem deBruijnNewmanBackwardHermite_coeff_of_lt :
    ∀ {n k : ℕ}, n < k → (deBruijnNewmanBackwardHermite n).coeff k = 0 := by
  intro n
  induction n with
  | zero =>
      intro k hk
      rw [deBruijnNewmanBackwardHermite, coeff_one]
      simp [Nat.ne_of_gt hk]
  | succ n ih =>
      intro k hk
      cases k with
      | zero => omega
      | succ k =>
          rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
            coeff_C_mul, coeff_derivative]
          rw [ih (by omega), ih (by omega)]
          ring

theorem deBruijnNewmanBackwardHermite_coeff_self :
    ∀ n : ℕ, (deBruijnNewmanBackwardHermite n).coeff n = 1 := by
  intro n
  induction n with
  | zero => simp [deBruijnNewmanBackwardHermite]
  | succ n ih =>
      rw [deBruijnNewmanBackwardHermite_succ, coeff_add, coeff_X_mul,
        coeff_C_mul, coeff_derivative, ih,
        deBruijnNewmanBackwardHermite_coeff_of_lt (show n < n + 2 by omega)]
      ring

theorem deBruijnNewmanBackwardHermite_coeff_of_odd_add {n k : ℕ}
    (hnk : Odd (n + k)) :
    (deBruijnNewmanBackwardHermite n).coeff k = 0 := by
  induction n generalizing k with
  | zero =>
      rw [zero_add] at hnk
      exact deBruijnNewmanBackwardHermite_coeff_of_lt hnk.pos
  | succ n ih =>
      cases k with
      | zero =>
          rw [deBruijnNewmanBackwardHermite_coeff_succ_zero, ih, mul_zero]
          rwa [Nat.succ_add_eq_add_succ] at hnk
      | succ k =>
          have hfar : Odd (n + (k + 2)) := by
            simpa only [Nat.succ_add_eq_add_succ, Nat.add_assoc] using hnk
          have hnear : Odd (n + k) := by
            have h' : Odd ((n + k) + 2) := by
              simpa only [Nat.add_assoc] using hfar
            exact (Nat.odd_add.mp h').mpr even_two
          rw [deBruijnNewmanBackwardHermite_coeff_succ_succ,
            ih hnear, ih hfar, mul_zero, add_zero]

theorem deBruijnNewmanBackwardHermite_even_const_odd_linear_pos (k : ℕ) :
    0 < (deBruijnNewmanBackwardHermite (2 * k)).coeff 0 ∧
      0 < (deBruijnNewmanBackwardHermite (2 * k + 1)).coeff 1 := by
  induction k with
  | zero => norm_num [deBruijnNewmanBackwardHermite]
  | succ k ih =>
      have hconst :
          0 < (deBruijnNewmanBackwardHermite (2 * k + 2)).coeff 0 := by
        rw [(by omega : 2 * k + 2 = (2 * k + 1) + 1),
          deBruijnNewmanBackwardHermite_coeff_succ_zero]
        have hlin := ih.2
        positivity
      constructor
      · simpa only [Nat.mul_succ] using hconst
      · rw [(by omega : 2 * (k + 1) + 1 = (2 * k + 2) + 1),
          deBruijnNewmanBackwardHermite_coeff_succ_succ]
        have hnonneg := deBruijnNewmanBackwardHermite_coeff_nonneg (2 * k + 2) 2
        positivity

theorem deBruijnNewmanBackwardHermite_natDegree (n : ℕ) :
    (deBruijnNewmanBackwardHermite n).natDegree = n := by
  apply natDegree_eq_of_le_of_coeff_ne_zero
  · rw [natDegree_le_iff_coeff_eq_zero]
    intro k hk
    exact deBruijnNewmanBackwardHermite_coeff_of_lt hk
  · rw [deBruijnNewmanBackwardHermite_coeff_self]
    norm_num

theorem deBruijnNewmanBackwardHermite_monic (n : ℕ) :
    (deBruijnNewmanBackwardHermite n).Monic := by
  rw [Monic, leadingCoeff, deBruijnNewmanBackwardHermite_natDegree,
    deBruijnNewmanBackwardHermite_coeff_self]

theorem deBruijnNewmanBackwardHermite_comp_neg_X :
    ∀ n : ℕ, (deBruijnNewmanBackwardHermite n).comp (-X) =
      C ((-1 : ℝ) ^ n) * deBruijnNewmanBackwardHermite n := by
  intro n
  induction n with
  | zero => simp [deBruijnNewmanBackwardHermite]
  | succ n ih =>
      have hderiv :
          -(deBruijnNewmanBackwardHermite n).derivative.comp (-X) =
            C ((-1 : ℝ) ^ n) * (deBruijnNewmanBackwardHermite n).derivative := by
        simpa only [derivative_comp, derivative_neg, derivative_X, neg_one_mul,
          derivative_mul, derivative_C, zero_mul, zero_add] using
          congrArg derivative ih
      have hderiv' :
          (deBruijnNewmanBackwardHermite n).derivative.comp (-X) =
            -(C ((-1 : ℝ) ^ n) *
              (deBruijnNewmanBackwardHermite n).derivative) :=
        neg_eq_iff_eq_neg.mp hderiv
      rw [deBruijnNewmanBackwardHermite_succ, add_comp, mul_comp, X_comp,
        ih, mul_comp, C_comp, hderiv', pow_succ]
      rw [C_mul]
      norm_num
      ring

theorem deBruijnNewmanBackwardHermite_eval_pos (n : ℕ) {x : ℝ} (hx : 0 < x) :
    0 < (deBruijnNewmanBackwardHermite n).eval x := by
  rw [eval_eq_sum_range, deBruijnNewmanBackwardHermite_natDegree]
  refine Finset.sum_pos'
    (fun k _ ↦ mul_nonneg (deBruijnNewmanBackwardHermite_coeff_nonneg n k)
      (pow_nonneg hx.le k)) ⟨n, by simp, ?_⟩
  rw [deBruijnNewmanBackwardHermite_coeff_self, one_mul]
  positivity

theorem deBruijnNewmanBackwardHermite_eval_ne_zero_of_ne_zero (n : ℕ) {x : ℝ}
    (hx : x ≠ 0) :
    (deBruijnNewmanBackwardHermite n).eval x ≠ 0 := by
  rcases lt_or_gt_of_ne hx with hxneg | hxpos
  · have hpositive := deBruijnNewmanBackwardHermite_eval_pos n (neg_pos.mpr hxneg)
    have hparity :
        (deBruijnNewmanBackwardHermite n).eval (-x) =
          (-1 : ℝ) ^ n * (deBruijnNewmanBackwardHermite n).eval x := by
      simpa [eval_comp] using congrArg (Polynomial.eval x)
        (deBruijnNewmanBackwardHermite_comp_neg_X n)
    intro hzero
    rw [hzero, mul_zero] at hparity
    linarith
  · exact ne_of_gt (deBruijnNewmanBackwardHermite_eval_pos n hxpos)

theorem deBruijnNewmanBackwardHermite_im_ne_zero_of_aeval_eq_zero
    {n : ℕ} {z : ℂ} (hz : (deBruijnNewmanBackwardHermite n).aeval z = 0)
    (hz0 : z ≠ 0) :
    z.im ≠ 0 := by
  intro him
  have hzreal : z = (z.re : ℂ) := by
    apply Complex.ext
    · simp
    · simpa using him
  have hzre : z.re ≠ 0 := by
    intro hre
    apply hz0
    rw [hzreal, hre]
    norm_num
  have heval : (deBruijnNewmanBackwardHermite n).eval z.re = 0 := by
    rw [hzreal, aeval_def] at hz
    change (deBruijnNewmanBackwardHermite n).eval₂ (algebraMap ℝ ℂ)
      ((algebraMap ℝ ℂ) z.re) = 0 at hz
    rw [eval₂_hom] at hz
    exact Complex.ofReal_eq_zero.mp hz
  exact deBruijnNewmanBackwardHermite_eval_ne_zero_of_ne_zero n hzre heval

private theorem exists_nonzero_deBruijnNewmanBackwardHermite_aeval_eq_zero
    (n : ℕ) (hn : 2 ≤ n) :
    ∃ z : ℂ, z ≠ 0 ∧ (deBruijnNewmanBackwardHermite n).aeval z = 0 := by
  rcases Nat.even_or_odd' n with ⟨k, rfl | rfl⟩
  · have hdegree : 0 < (deBruijnNewmanBackwardHermite (2 * k)).degree := by
      rw [← natDegree_pos_iff_degree_pos,
        deBruijnNewmanBackwardHermite_natDegree]
      omega
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_aeval_eq_zero ℂ
      (deBruijnNewmanBackwardHermite (2 * k)) hdegree.ne'
    refine ⟨z, ?_, hz⟩
    intro hz0
    subst z
    rw [aeval_def, eval₂_at_zero] at hz
    have hcoeffzero :
        (deBruijnNewmanBackwardHermite (2 * k)).coeff 0 = 0 := by
      apply FaithfulSMul.algebraMap_injective ℝ ℂ
      simpa using hz
    have hcoeffpos :=
      (deBruijnNewmanBackwardHermite_even_const_odd_linear_pos k).1
    linarith
  · let p := deBruijnNewmanBackwardHermite (2 * k + 1)
    let q := p.divX
    have hcoeffzero : p.coeff 0 = 0 := by
      apply deBruijnNewmanBackwardHermite_coeff_of_odd_add
      simp
    have hqcoeffpos : 0 < q.coeff 0 := by
      simpa [q, p, coeff_divX] using
        (deBruijnNewmanBackwardHermite_even_const_odd_linear_pos k).2
    have hqdegree : 0 < q.degree := by
      rw [← natDegree_pos_iff_degree_pos]
      simp only [q, natDegree_divX_eq_natDegree_tsub_one, p,
        deBruijnNewmanBackwardHermite_natDegree]
      omega
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_aeval_eq_zero ℂ q hqdegree.ne'
    have hz0 : z ≠ 0 := by
      intro hz0
      subst z
      rw [aeval_def, eval₂_at_zero] at hz
      have hcoeffzero' : q.coeff 0 = 0 := by
        apply FaithfulSMul.algebraMap_injective ℝ ℂ
        simpa using hz
      linarith
    refine ⟨z, hz0, ?_⟩
    have hfactor : X * q = p := by
      simpa [q, hcoeffzero] using X_mul_divX_add p
    change p.aeval z = 0
    rw [← hfactor]
    simp [hz]

theorem exists_deBruijnNewmanBackwardHermite_aeval_eq_zero_im_pos
    (n : ℕ) (hn : 2 ≤ n) :
    ∃ z : ℂ, 0 < z.im ∧ (deBruijnNewmanBackwardHermite n).aeval z = 0 := by
  obtain ⟨z, hz0, hz⟩ :=
    exists_nonzero_deBruijnNewmanBackwardHermite_aeval_eq_zero n hn
  have him := deBruijnNewmanBackwardHermite_im_ne_zero_of_aeval_eq_zero hz hz0
  by_cases hupper : 0 < z.im
  · exact ⟨z, hupper, hz⟩
  · have hlower : z.im < 0 := lt_of_le_of_ne (le_of_not_gt hupper) him
    refine ⟨-z, by simpa using neg_pos.mpr hlower, ?_⟩
    have hidentity := congrArg (fun p : ℝ[X] ↦ p.aeval z)
      (deBruijnNewmanBackwardHermite_comp_neg_X n)
    simpa [aeval_comp, hz] using hidentity

end

end LeanLab.Riemann
